### ISSUE TITLE
Silent yaml package dependency

### ISSUE THREAD

**Issue by JanuszL** [webdataset/webdataset#104]
Hi,

It seems that https://github.com/webdataset/webdataset/commit/f2eef2d1d2c9371412c53ce41c0a1e6453c49ad9 adds a silent yaml python package dependency while https://github.com/webdataset/webdataset/blob/master/setup.py misses it in the `install_requires` section.

**Comment by rom1504** [comment]
indeed this makes the last version uninstallable, please fix

**Comment by tmbdev** [comment]
I've added it as a dependency. Not sure why the tests didn't pick it  up.

**Comment by JanuszL** [comment]
Thanks @tmbdev.
