### ISSUE TITLE
Mitigation of Dataset depreciation

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [webdataset/webdataset#107]
Hello,

I see that `Dataset` is now depreciated. What is the migration procedure ?

In particular:

- How to support `__len__` for cases where it is known ?
- It seems that `shardshuffle` is not available anymore on `Webdataset` how to enable iterating over shards in a different order at each call of `iter` ?

Thanks for the help!

**Comment by AndreaBrg** [comment]
Hi, did you every find out the solution? I'm facing the same problem.

**Comment by brtasavpatel** [comment]
same for me.

**Comment by brtasavpatel** [comment]
from what I can tell from tracing the code and debugging is that, `shardshuffle` is not required anymore. by default `Webdataset` function shuffles the urls.
As you can see here ultimately this class gets called and here : https://github.com/webdataset/webdataset/blob/master/webdataset/dataset.py#L76

and `shuffle=True` by default : https://github.com/webdataset/webdataset/blob/master/webdataset/shardlists.py#L190

**Comment by tmbdev** [comment]
You can specify a nominal length using the `with_length` method (you can force the actual epoch length with the `with_epoch` method).

**Comment by GuillaumeLeclerc** [comment]
How do we *not* shuffle for validation then ?
