### ISSUE TITLE
Usage for Graph Neural Networks

### ISSUE THREAD

**Issue by michaltakac** [webdataset/webdataset#109]
How should webdataset be used for storing graph representation of a mesh (used for training [MeshGraphNets](https://github.com/deepmind/deepmind-research/tree/master/meshgraphnets)) in tar files? I'm thinking about JSON, but that would make the tar file big, so maybe pickle? And how the decoding function would look like for JSON or Pickle data?

**Comment by tmbdev** [comment]
You can store individual files in compressed format, so just use `data.json.gz`. Files with extensions of `.json`, `.json.gz`, `.pyd`, and `.pyd.gz` get decoded automatically by WebDataset, so you don't need to do anything.

Alternatively, you can use any of the standard mesh file formats used in science and engineering if there are Python readers for it. For decoding, you just need to write a function that takes a byte array as input and returns the decoded data. Inside that function, you usually either turn the byte array into an io.ByteIO object or just write it to disk; either way, you use the mesh library's reader to read in the data.
