### ISSUE TITLE
Processor has no len()

### ISSUE THREAD

**Issue by ARKseal** [webdataset/webdataset#110]
Hey, I've been using deepspeed with Webdataset and I've been getting this error: `TypeError: object of type 'Processor' has no len()`. The script works version 0.1.62 (didn't try any other). I believe it has to do with the removal of length in `wds.WebDataset` and the other classes. Could this change be reverted?

**Comment by tmbdev** [comment]
The `__len__` method was removed by default because some libraries use the presence of `__len__` to determine whether a dataset is iterable.

Just use the `with_length` method:

```
dataset = WebDataset(...)
dataset = dataset.with_length(n)
```

Note that this is commonly combined with `with_epoch`:

```
dataset = WebDataset(...)
dataset = dataset.repeat().with_epoch(n).with_length(n)
```
