### ISSUE TITLE
Remove torch from dependencies

### ISSUE THREAD

**Issue by danielgafni** [webdataset/webdataset#118]
WebDataset 0.1.76 which I was using before doesn't have `torch` as a dependency. However, newer versions do.

I don't think it's a good idea since `TarWriter` (and maybe other `webdataset` parts) can be used for creating the dataset in a solely data processing environment. Bringing in a huge (`torch` 1.10.0 is 1.8 GB!) dependency is a very big overhead. 

What do you guys this?

**Comment by tmbdev** [comment]
I don't see "torch" in either requirements.txt or setup.py; torch was removed as a dependency several versions back.

Where do you see it listed as a dependency?

**Comment by danielgafni** [comment]
It’s not on requirements, however, the last time I tried to run my code with the newest WebDataset version it crashed somewhere on “import torch”. The problem disappeared after I downgraded WebDataset version. I’ll send you the specific error in a few days after my vacation. Thanks for looking into it!

**Comment by tmbdev** [comment]
Ah, thanks. I’ll try to find that and/or add a test case.

**Comment by tmbdev** [comment]
I think I found the place where torch was accidentally imported.

If you still get errors related to unexpected torch imports, please provide a traceback and line numbers.

**Comment by rom1504** [comment]
could you make a new release with that change?
