### ISSUE TITLE
How to extend the webdataset to make it into a custom dataset  with getitem function as described below

### ISSUE THREAD

**Issue by Griffintaur** [webdataset/webdataset#121]
I have a custom dataset like these where `__getitem__ `look like this:
```
def __getitem__ (self,index):
    clip=[ ]
    for i in range(16):
         file_name = list_of_files[index- i]
         file_path = os.path.join(base_path, filename)
         clip.append(Image.open(file_path).convert('RGB'))
     ### further preprocessing which are important 
     return clip,label
```
    
  How can I perform this by extending the web dataset?
  Any info or pointers on this would be helpful?
  sorry for this naive question, I am new to this.

**Comment by tmbdev** [comment]
I'm afraid I don't understand the question. Maybe this helps.

Pytorch has two different kinds of data sets: indexed and iterable. An indexed dataset has a `__getitem__` and `__len__` method; an iterable dataset has neither. DataLoader works with both iterable and indexed datasets, though it behaves subtly different.

WebDataset implements iterable datasets. WebDataset also avoid you having to mess around with individual files, and it represents processing as pipelines. So, the webdataset equivalent of what you are writing would be something like:

```Bash
$ tar cf dataset.tar *.jpg
```

```Python
def process_sample(sample):
   ### further important preprocessing
   returns sample

dataset = WebDataset("dataset.tar").decode("rgb").map(process_sample)
```
