### ISSUE TITLE
Docs about decoding is incorrect

### ISSUE THREAD

**Issue by YOUSIKI** [webdataset/webdataset#123]
Well, webdataset is surely a great work for PyTorch users. Thanks a lot for the authors.

But recently I found that the documents for webdataset have many typos and mistakes. For example, I wanted to write a decoder and the [related document](https://webdataset.github.io/webdataset/decoding/) was wrong.

The problem was caused by the misuse of `wds.filters.Curried` and `wds.filters.Curried2`. 

I also found a workaround: to write a user-defined decoder, the user should wrap the decoder (which only takes a `sample` as input) to an iterator and use `wds.Processor(dataset, wrapped_decoder)`.

I'm not sure whether I understand the purpose of `wds.filters.Curried`, I think maybe is should be rewrite like this:

```python
class Curried(object):

    def __init__(self, f):
        """Store the function for future currying."""
        self.f = f

    def __call__(self, data, *args, **kw):
        """Curry with the given arguments."""
        return Curried2(self.f, *args, **kw)(data)
```

This can fix the problem.

I wrote some examples in [Colab notebook](https://colab.research.google.com/drive/1_rxlj79lrI3SSoelwFpE7xW69_trcx4u?usp=sharing), please refer to this for details.

Further more, I think `mageio.imread` in document should be `imageio.imread`. 😁

Maybe the document should be fixed, or `wds.filters` should be fixed. I'd like to contribute but I don't know how...

Thanks again.

**Comment by YOUSIKI** [comment]
I just found that in branch `v2` there are a lot of changes. Maybe this issue will be fixed in `v2` ?

**Comment by tmbdev** [comment]
Thanks for the report.

The documentation is generated from runnable notebooks, so the code was working correctly at some point; however, the documentation notebooks are not run as testcases right now, so they can get outdated relative to the libraries.

Yes, v2 is in development; it will feature a simpler API that's easier to document and extend, and I'll be updating the documentation for that as well.

TODO: look into incorporating the documentation notebooks as testcases

**Comment by tmbdev** [comment]
The README notebook is executing correctly with v2.
