### ISSUE TITLE
Does webdataset support horovod?

### ISSUE THREAD

**Issue by lguduy** [webdataset/webdataset#124]
Hi, does webdataset support horovod? If so, are there best practices? please provide some examples, thanks a lot!

**Comment by tmbdev** [comment]
WebDataset just provides standard IterableDataset instances, so I don't see why it shouldn't work with Horovod.

I'll try to add an example once v2 is out.

**Comment by lguduy** [comment]
> WebDataset just provides standard PyTorch IterableDataset instances, so I don't see why it shouldn't work with Horovod.
> 
> I'll try to add an example once v2 is out.

Thanks for your reply. When will the v2 come out?

**Comment by tmbdev** [comment]
You can already check it out as branch v2. It is largely backwards
compatible.

I will probably switch it over in a few weeks as the default.

Tom

**Comment by MarkYangjiayi** [comment]
@tmbdev But in wds we use the standard pytorch ddp apis right? Is it compatible with horovod apis? For instance, hvd.rank() and torch.distributed.get_rank().

**Comment by rwightman** [comment]
@tmbdev I'm trying to figure out how to use webdataset with distributed mechanisms that don't use torch.distributed

Neither horovod or PyTorch XLA (TPU) will have an initialized torch.distributed process group where you can query the rank / world_size, etc. The current master appears to assume that is always possible.

I see references in the docs to (a deprecated?) ShardList where one could pass in a custom split_by_node fn, in v2 I potentially see a different scheme but not sure if it's finished. Something like that would be preferred to assuming it can always be handled internally.

Either way, for the code I'm currently working on I guess I need to write my own PytorchShardList class? Something to consider for future dev... also the env vars across the various distributed setups are not consistent, I'm aware of at least 4 so making it easy to pass in a custom fn is probably best.

**Comment by dvornikita** [comment]
Hi @rwightman, I'm using horovod and facing the same problem. What did you end up doing in your case, writing your own PytorchShardList class?

Thank you,
Nikita

**Comment by tmbdev** [comment]
You have complete control over splitting. You can use the fluid interface, but it's clearer with the pipeline interface:

```
def my_node_splitter(source):
    for shard in source:
        if ...whatever...:
            yield shard

dataset = wds.DataPipeline(
    wds.SimpleShardList(url),
    # at this point we have an iterator over all the shards
    wds.shuffle(100),
    my_node_splitter,        # <<<===
    wds.split_by_worker,
    # at this point, we have an iterator over the shards assigned to each worker
    wds.tarfile_to_samples(),
    wds.shuffle(1000),
    wds.decode("torchrgb"),
    # at this point, we have an list of decompressed training samples from each shard in this worker in sequence
    get_patches,  # note that can put iterator->iterator functions into the pipeline directly
    wds.shuffle(10000),
    wds.to_tuple("big.jpg", "json"),
    wds.batched(16)
)
```
