### ISSUE TITLE
Custom batching

### ISSUE THREAD

**Issue by tadejsv** [webdataset/webdataset#127]
Is custom batching (selecting items from the buffer to put in a batch) possible?

My use case is for contrastive learning: I would like to take N items from M classes from the buffer and put them in a batch. I would structure the dataset in a way that such selection should be possible (with a large enough buffer size). Or is there a better way to do it?

**Comment by tmbdev** [comment]
The way to write code like that is to maintain a reservoir of samples in memory. Here is a simple function (untested) that yields batches with one sample per class:

```Python
def batch_with_one_per_class(src):
    buffer = [[] for _ in range(10)]
    for sample in src:
        buffer[sample["cls"]].append(sample)
        if [] in buffer:
            continue
        batch = [c.pop() for c in buffer]
        yield batch
````

You then say something like: `ds = WebDataset(...).decode(...).then(batch_with_one_per_class)`

**Comment by tadejsv** [comment]
I'll give it a try, thank you very much

**Comment by tadejsv** [comment]
I was able to construct a batching function -
