### ISSUE TITLE
problem with creating a tar dataset that has named tuples in it

### ISSUE THREAD

**Issue by Zevrap-81** [webdataset/webdataset#130]
I am getting the following error related to pickling when i try to save my dataset using TarWriter

```_pickle.PicklingError: Can't pickle <class 'data.input'>: attribute lookup input on data failed```

I tried to look up the error but could not find a reasonable solution so i am opening an issue here.

My data class is as follows(have only the main components to reproduce the problem). It returns two named tuples input and output

```
class Data(Dataset):
    '''
        Interface class to load all the data and to call geomdata class to process it
    '''
    def __init__(self, data_path):
        super().__init__()

        self.Input= namedtuple("input", ["coords"]) 
        self.Output= namedtuple("output", ["disps"])

    def len(self):
        return self.data.n_exps
    
    def __getitem__(self, idx):

        coords= np.zeroes(10,1)

        disps= np.zeroes(10,1)
        
        input= self.Input(coords=coords)
        output= self.Output(disps=disps)
        return (input, output)
```
I used this code to save the data in tar format
```
path= "/data"
dataset= Data(path)

sink = wds.TarWriter("/data/data.tar")

for idx, (input, output) in enumerate(dataset):
    sink.write({
        "__key__": "sample%06d" % idx,
        "input.pyd": input,
        "output.pyd": output,
    })
sink.close()
```
Can you please look into this error?

**Comment by tmbdev** [comment]
`namedtuple` creates a new class. You call that class `input` but store it in the variable `self.Input`, so the pickler can't find it by its class name. You can fix this error by replacing the code you have with a top-level assignment of `Input = namedtuple("Input", ["coords"])`. But if you do that, your file can't be unpickled by anything other than this exact main program, and that's probably not what you want. Sadly, named tuples and dataclasses just aren't well integrated into Python.

Ugly as it is, your best bet is to only store tuples, lists, dicts, and tensors in .pyd files.
