### ISSUE TITLE
Webdataset creation using Apache Spark

### ISSUE THREAD

**Issue by naveenkumarmarri** [webdataset/webdataset#132]
Thank you for creating this library which helps to scale train models to very large datasets.

Right now the only way to programmatically create tar files  is using `ShardWriter` or `TarWriter`
For example
```
with wds.ShardWriter('shards/shard-%07d.tar',maxcount=10000) as sink:
        for idx, line in enumerate(get_yfcc_dataset()):
            sink.write({
                '__key__': "%07d"%idx,
                'img': str(line['cid']),
                'txt': line['title']
                })
```
From the above implementation it quickly becomes a bottleneck for very large datasets(~Billion rows), because the write operation happens sequentially. 
I'm wondering if it possible to integrate webdataset library with pyspark to write to shards in parallel.

**Comment by tmbdev** [comment]
Parallel writing needs to be handled at the "job" level, not at the level of the `TarWriter`. Pseudocode looks something like:

```Python
def write_ith_shard(i, nshards):
    source = open_source_dataset()
    sink = wds.TarWriter("shard-%06d.tar")
    for k in range(i, len(source), nshards):
        sample = source[i]
        sample["__key__"] = "%09d" % i
        sink.write(sample)
    sink.close()
    return "done %d" % i
```

You can parallelize this any way you like. For example, if you use Ray, you can write:

```Python
def main():
    ray.init()
    n = 200
    f = ray.remote(write_ith_shard)
    result = ray.get([f.remote(i, n) for i in range(n)]) 
```

**Comment by normster** [comment]
Hi @tmbdev,

The pseudocode you sketched out samples images evenly along the dataset for each shard, would changing this to a uniform random sampling improve randomness or does it not matter because the `.shuffle` filter is good enough?
