### ISSUE TITLE
How to split Webdataset?

### ISSUE THREAD

**Issue by brtasavpatel** [webdataset/webdataset#135]
I need some suggestions on how can to split a webdataset into test, train and validation sets?

**Comment by tmbdev** [comment]
If your data is shuffled and split into separate shards, say "data-{000000..000120}.tar", you can simply pick any subset of the shards.

For example:

```Bash
$ my-training-job --training-shards 'data-{000000..000099}.tar' --val-shards 'data-{000100..000119}.tar'
```

Of course, you may want to rename the shards to make the split more obvious.

For shuffling and other kinds of splitting operations, have a look at: 

https://github.com/webdataset/tarp
