### ISSUE TITLE
Shardcache not closing if shard byte size is divisible by read byte size

### ISSUE THREAD

**Issue by abhi-mosaic** [webdataset/webdataset#145]
I've been having issues cacheing datasets pulled from S3, where some shard caches are not triggering `self.close(complete=True)`. When I look at the cache folder, the shards are all 100% there but a few will still have their temp name with suffix `~...~`. Manually removing the suffix from those few shards allows me to read the webdatset from cache just fine. 

I think this behavior is because the last call to `CacheStream.read(n)` is not happening if the shard byte size is perfectly divisible by the read byte size `n`. So there is no final call (where data is expected to be `None`) and this block is not getting triggered:

https://github.com/webdataset/webdataset/blob/d616fe4eac6715c939d1511e6c9348319dc5e057/webdataset/shardcache.py#L76-L79

I was able to fix the issue locally by just removing all `self.close(complete=True)` calls inside of `CacheStream`, and just manually calling `close()` at the end of the iterator, inside `def cache_shards(...)`:

```python
def cache_shards(urls, cache_dir="./data", cache_size=1e15, cache_name=guess_shard, verbose=False):
...
    if not os.path.exists(cache_path):
        _cache = CacheStream(cache_path, stream, verbose=verbose)
        yield dict(url=url, stream=_cache)
        _cache.close(complete=True)
```

I'm not 100% sure if this is a good fix though... would love to get a second opinion / merge a stable fix!

**Comment by tmbdev** [comment]
Thanks. This code has been rewritten in v2 (soon to go live).
