### ISSUE TITLE
DALI parallel external source

### ISSUE THREAD

**Issue by austinmw** [webdataset/webdataset#150]
Hi,

I've followed DALI's example [WebDataset integration using External Source](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/use_cases/webdataset-externalsource.html#WebDataset-integration-using-External-Source). 

When I tried to switch from a local to an S3 url, I noticed slow performance, so tried to move to DALI's example [Parallel External Source](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source.html#Parallel-External-Source), however it seems to want a callable instead of iterable.

So do you know if it's possible to use webdataset in conjunction with DALI parallel external source, or alternatively, to improve DALI remote url performance by prefetching in some other way?

**Comment by tmbdev** [comment]
I believe DALI is working on direct, efficient S3 support for WebDataset format files. Once that is out, you shouldn't need the WebDataset library at all (DALI's efficiency comes from moving a lot of code into C++). I don't know DALI well enough to know whether there are any short term workarounds.
