### ISSUE TITLE
[Feature request] Add support for data in HDFS

### ISSUE THREAD

**Issue by gau-nernst** [webdataset/webdataset#161]
Hello, is there a plan to support reading data from HDFS? From what I see from the code, it can be implemented by adding a new dispatch method in `gopen.py`

The command for reading HDFS file

```bash
hdfs dfs -cat {url}
```

**Comment by rom1504** [comment]
This already works by using exactly the command you're suggesting
Webdataset supports any command that can output tar bytes

**Comment by gau-nernst** [comment]
Got it. I saw that you can do it by prepending `pipe:` to the hdfs command . Thanks!

**Comment by tmbdev** [comment]
I may add this as a default command for hdfs URLs
