### ISSUE TITLE
syntax error in 0.2.4 release

### ISSUE THREAD

**Issue by czmrand** [webdataset/webdataset#166]
Getting a syntax error on .../webdataset/cache.py", line 43
while data := stream.read(chunk_size):
Looks like := is a valid syntax from python 3.8.
Is webdataset limited to python >= 3.8?

**Comment by JanuszL** [comment]
I see the same problem here.
Some users may still use Ubuntu 18.04 where the default python 3.x is 3.6 there.
If you aim to support python >= 3.9 you need to update (setup.py)[https://github.com/webdataset/webdataset/blob/main/setup.py#L30] so the users with older python won't upgrade to an incompatible version:
```
 classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9"
    ],```

**Comment by rwightman** [comment]
@tmbdev maintaining Python / PyTorch libs myself, biggest reason is colab and kaggle, both are always well behind the latest (currently 3.7) and heavily used by the PyTorch user base for various ML tasks....

**Comment by reuben** [comment]
> Yes, WebDataset is intended for Python 3.9 and over. Python 3.9 has been out for over two years and is used with most of the PyTorch distributions.

Then you should consider updating the setup.py script to enforce this. Currently it advertises Python 3.6 support. You can use the [python_requires](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) key to prevent the package being installed on older versions.

**Comment by reuben** [comment]
Seemed like a shame to lose Python 3.7 support over a single line so I've fixed it here: https://github.com/reuben/webdataset and also modified CI so that it's tested and built on all Python versions rather than just 3.9. It's published [here](https://pypi.org/project/webdataset-py36/), I'll set up a bot to automatically merge upstream changes but can't promise speed.

**Comment by JanuszL** [comment]
@reuben - can you post a PR to this repo so the fix reenabling support for the older python version is included in the next release?

**Comment by reuben** [comment]
@JanuszL opened PR #168 168

**Comment by tmbdev** [comment]
Thanks. That PR included other stuff. I have added backwards compatibility now. Please give it a try.
