### ISSUE TITLE
Cannot import name 'PytorchShardList' from 'webdataset'

### ISSUE THREAD

**Issue by luomingshuang** [webdataset/webdataset#171]
When I use this package, I run the command: 
`from webdataset import PytorchShardList`.
 
But I get a bug as following:
`ImportError: cannot import name 'PytorchShardList' from 'webdataset' (/ceph-meixu/luomingshuang/anaconda3/envs/k2-python/lib/python3.8/site-packages/webdataset/__init__.py)`.

I have a look for the file `/ceph-meixu/luomingshuang/anaconda3/envs/k2-python/lib/python3.8/site-packages/webdataset/__init__.py`. And I find there is no function named `PytorchShardList`. Does the function miss?

**Comment by tmbdev** [comment]
PytorchShardList is in 0.1. You probably want to replace it with SimpleShardList.
