### ISSUE TITLE
Can't import module iterators

### ISSUE THREAD

**Issue by nicoduchene** [webdataset/webdataset#175]
The newest release on pip (0.2.x) doesn't package the iterators module. 
Is there a workaround other than installing an older version?
Is the iterators module being replaced or dropped?
If it is, it would be good to update the API docs to reflect that.

Thanks

**Comment by tmbdev** [comment]
The functionality from iterators.py is now found in filters.py. The uncurried functions have been renamed to something like `_shuffle`, and the curried functions have the names without the underscore.

So, if in v1 you used `shuffle(data, arg1, arg2)`, you now use `shuffle(arg1, arg2)(data)`
