### ISSUE TITLE
Multinode training error when using singlenode training

### ISSUE THREAD

**Issue by ZeWang95** [webdataset/webdataset#178]
Hello!

I was trying to adapt a code with webdataset==0.1.103 support to webdataset==0.2.5.
The script launches pytorch distributed training on a single node with 8 gpus, and I got the following error:
ValueError: input pipeline needs to be reconfigured for multinode training

May I ask how should I fix this?
Thank you!

**Comment by yoanisgil** [comment]
Not sure if you fixed your issue, but you have to provide the nodesplitter. In my case this is what I did:

```python
wds.WebDataset(
                shard_url,
                handler=warn_and_continue,
                nodesplitter=shardlists.split_by_node,
            )
```

Hope it helps.

**Comment by tmbdev** [comment]
I've updated the error message; I hope it's clearer now.
