### ISSUE TITLE
How can we understand this "It is generally most efficient to avoid batching in the `DataLoader` altogether; instead, batch in the dataset and then rebatch after the loader."

### ISSUE THREAD

**Issue by zh794390558** [webdataset/webdataset#187]

**Comment by tmbdev** [comment]
This is the recommendation of PyTorch's DataLoader for streaming datasets. There are several reasons for this, foremost the fact that data needs to be transferred between different processes when using `num_workers` greater than zero and that data transfer is more efficient the larger the amount of data you transfer at a time.

You can still batch/rebatch in the DataLoader using the WebDataset Dataloader, as in the example:

```
loader = wds.WebLoader(dataset, num_workers=4, batch_size=8)
loader = loader.unbatched().shuffle(1000).batched(12)
```
