### ISSUE TITLE
Process hang with DDP training

### ISSUE THREAD

**Issue by poor1017** [webdataset/webdataset#188]
I use webdataset in SpeechBrain. And I found there are 2 cases the process will hang in DDP training:

1. `num_workers` is set too large, set it to 1 is definitely safe;
2. There is only one shard file, `shard-000000.tar`. I set `samples_per_shard` to a small value, and shard files are more than one, the problem solved.

My solution is a workaround, and I think there must be a stardard way to process the situation.

Thank you!

**Comment by tmbdev** [comment]
I haven't seen this problem in DDP training; let me see whether I can reproduce.

Can you provide your pipeline, please?

**Comment by poor1017** [comment]
https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxLingua107/lang_id/train.py
You can refer this script. Keep train, valid, test data as small as possible, you  should get the bug.

**Comment by rwightman** [comment]
@poor1017 you don't have enough shard files to distribute amongst the dataloader workers across all train processes. If a train process ends up with no shards, it will hangs training as one of the nodes can't step. You should ensure you shard your data with enough shards to distribute to all workers (or reduce the num workers and number of processes to fit what you have). Sampling with replacement should work too.

**Comment by poor1017** [comment]
@rwightman Yes, you are right. Maybe we should output a warning for this situation.
