### ISSUE TITLE
Doc recommendations on loading long duration media files (e.g. audio, video)

### ISSUE THREAD

**Issue by njb** [webdataset/webdataset#189]
Hello, I’m trying out webdataset and loving it. For several audio/video data generation tasks I have, however, I’m not sure the best practice for storing/loading long duration media files (e.g. music files that are 3 minutes each). 

In more detail, I have several datasets that contain many 2-3 minute audio files. Typically, I write a data loader to select a random file, then load a short segment from within the file without having to load the entire file. For example, this can be accomplished using `torchaudio.load` with the `frame_offset` and `num_frames` optional arguments or `numpy.load(file_path, mmap_mode=‘r’)`.

Is there a way to use webdataset to iterate through longer duration media assets with partial (sliced) loads from within a tar? (So the load only loads a random short chunk of a longer file?)

**Comment by njb** [comment]
@manosplitsis I've just been pre-slicing longer files and saving chunks, following the advice on videos.

**Comment by tmbdev** [comment]
Yes, the recommended way of dealing with this is to pre-split the videos in a preprocessing step. In many cases, splitting it down to clips of a few seconds and then shuffling the new clip-based dataset is a good idea.

Alternatively, you can use the `wids` library; in that case, the data will just be memory-mapped from disk, and your video decoder may be able to seek and decode subsets without consuming any additional memory.
