### ISSUE TITLE
rsample() is too slow

### ISSUE THREAD

**Issue by slyviacassell** [webdataset/webdataset#196]
After testing the rsample(), I found it too slow since it still read the whole data stream. I wonder whether there is another implementation for the subsampling?

**Comment by tmbdev** [comment]
WebDataset is optimized for streaming processing, so in general you can't use random access on the tar file. Furthermore, tar files don't have any meta information helping with random access; all you can do is scan them sequentially. If your .tar file contains large files, sequential scanning may be faster than sequential reading, but it often isn't.

To keep things efficient, the probabilities you use with `rsample` shouldn't be too small, but the exact cutoff depends on your dataset and setup. With parallel I/O, it really doesn't matter that much.

Note that you can use `rsample` with shards, not just with samples, and there, you don't pay any overhead of sequential reading. So another strategy is to use more shards and rsample the shards.

(In addition, storage servers like AIStore can perform sampling for you on the server side and can use random access there.)

**Comment by slyviacassell** [comment]
> WebDataset is optimized for streaming processing, so in general you can't use random access on the tar file. Furthermore, tar files don't have any meta information helping with random access; all you can do is scan them sequentially. If your .tar file contains large files, sequential scanning may be faster than sequential reading, but it often isn't.
> 
> To keep things efficient, the probabilities you use with `rsample` shouldn't be too small, but the exact cutoff depends on your dataset and setup. With parallel I/O, it really doesn't matter that much.
> 
> Note that you can use `rsample` with shards, not just with samples, and there, you don't pay any overhead of sequential reading. So another strategy is to use more shards and rsample the shards.
> 
> (In addition, storage servers like AIStore can perform sampling for you on the server side and can use random access there.)

Thanks for your reply. As you mentioned, the efficient way is just to apply `rsample` on shards, not the samples. And this would not randomly access the tar file which could reduce the I/O.
