### ISSUE TITLE
AttributeError: module 'PIL' has no attribute 'Image'

### ISSUE THREAD

**Issue by oeway** [webdataset/webdataset#198]
It appears that `PIL` was not imported correctly in the `imageencoder`.  Currently, it import `PIL` via `import PIL` directly and refer to `Image` via `PIL.Image` which cause the no attribute error.

The correct way to do it is to do `from PIL import Image`.

This is a  quick test:
```python
>>> import PIL
>>> PIL.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL' has no attribute 'Image'
```

**Comment by Data-drone** [comment]
Any update on this one?

**Comment by ekorman** [comment]
one fix is adding `import PIL.Image` anywhere in your code (before calling `imageencoder`)

**Comment by gaikwadabhishek** [comment]
https://stackoverflow.com/questions/11911480/python-pil-has-no-attribute-image

**Comment by tmbdev** [comment]
I think it's fixed now.
