### ISSUE TITLE
Handlers don't catch ValueError for duplicate file names

### ISSUE THREAD

**Issue by dome272** [webdataset/webdataset#205]
```
Original Traceback (most recent call last):
  File "/home/dome/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dome/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/dome/.local/lib/python3.7/site-packages/webdataset/pipeline.py", line 68, in iterator
    for sample in self.iterator1():
  File "/home/dome/.local/lib/python3.7/site-packages/webdataset/filters.py", line 204, in _shuffle
    for sample in data:
  File "/home/dome/.local/lib/python3.7/site-packages/webdataset/filters.py", line 388, in _to_tuple
    for sample in data:
  File "/home/dome/.local/lib/python3.7/site-packages/webdataset/filters.py", line 293, in _map
    for sample in data:
  File "/home/dome/.local/lib/python3.7/site-packages/webdataset/filters.py", line 293, in _map
    for sample in data:
  File "/home/dome/.local/lib/python3.7/site-packages/webdataset/tariterators.py", line 172, in group_by_keys
    f"{fname}: duplicate file name in tar file {suffix} {current_sample.keys()}"
ValueError: 000020003.jpg: duplicate file name in tar file jpg dict_keys(['__key__', '__url__', 'jpg', 'json', 'txt'])
```

That is the error that I'm getting. Is there any way of catching / skipping this item?
I'm constructing the webdataset like this already: 
```
dataset = wds.WebDataset(args.dataset_path, resampled=True, handler=warn_and_continue).decode("rgb", handler=warn_and_continue).map(
        ProcessDataV3(), handler=warn_and_continue).to_tuple("jpg", "txt", handler=warn_and_continue).shuffle(690, handler=warn_and_continue)
```

Right now I always have to restart the training which is really tedious. I would appreciate any help 😄

**Comment by tmbdev** [comment]
Some of the stages inside the `WebDataset` class don't use handlers; that's probably a bug, I'll look into it.

You get complete control over error handling at every stage with the `DataPipeline` interface. The WebDataset class is just a convenience wrapper around this.

```Python
dataset = wds.DataPipeline(
    wds.SimpleShardList(url),
    # at this point we have an iterator over all the shards
    wds.shuffle(100),
    wds.split_by_worker,
    # at this point, we have an iterator over the shards assigned to each worker
    wds.tarfile_to_samples(),
    wds.shuffle(1000),
    wds.decode("torchrgb"),
    # at this point, we have an list of decompressed training samples from each shard in this worker in sequence
    get_patches,  # note that can put iterator->iterator functions into the pipeline directly
    wds.shuffle(10000),
    wds.to_tuple("big.jpg", "json"),
    wds.batched(16)
)
```

**Comment by marson666** [comment]
> 

DataPipe still doesn't work

`ds = wds.DataPipeline(
            wds.SimpleShardList(self.tar_file_list),
            # wds.ResampledShards(self.tar_file_list),
            wds.split_by_node,
            wds.split_by_worker,
            wds.tarfile_to_samples(handler=wds.warn_and_continue),
            wds.shuffle(1000, handler=wds.warn_and_continue),
            wds.decode("pilrgb", handler=wds.warn_and_continue),
            wds.to_tuple("jpg", "txt", handler=wds.warn_and_continue),
            wds.map_tuple(transform, truncate_caption, handler=wds.warn_and_continue),
            wds.batched(batch_size),
        )`

**Comment by marson666** [comment]
I chang to DataPipeline, it still doesn't work.
`
ds = wds.DataPipeline(
            wds.SimpleShardList(self.tar_file_list),
            wds.split_by_node,
            wds.split_by_worker,
            wds.tarfile_to_samples(handler=wds.warn_and_continue),
            wds.shuffle(1000, handler=wds.warn_and_continue),
            wds.decode("pilrgb", handler=wds.warn_and_continue),
            wds.to_tuple("jpg", "txt", handler=wds.warn_and_continue),
            wds.map_tuple(transform, truncate_caption, handler=wds.warn_and_continue),
            wds.batched(batch_size),
        )
`

**Comment by parkitny** [comment]
I am also hitting these issues, is there any plan to make progress on fixing this issue in the near future?

**Comment by drscotthawley** [comment]
@tmbdev What breaks if we just comment out that `ValueError` or replace it with a warning? 
Seems odd to crash the entire training run rather than just ignore one extra file.

**Comment by parkitny** [comment]
My solution for the time being had been to copy the group by keys implementation (causing the crash), remove the line raising the exception and monkey patch the web dataset library with the new function.

**Comment by tmbdev** [comment]
I've added the ability to specify a handler. (Sorry it took so long.)

However, having duplicate filenames really is a serious problem with the dataset, and I would recommend just regenerating the dataset itself.
