### ISSUE TITLE
[Documentation] How to change the batching/collate function?

### ISSUE THREAD

**Issue by PardoAlejo** [webdataset/webdataset#209]
Hi,

I have a dataset of image-text pairs. However, each image can have many text assigned to it.
I'd like to make sure that **every batch contains only one description per image**. But I'd like to still make sure that I use the whole dataset for training. In other words, **I wanna use all the texts but make sure that within the same batch there is no text coming from the same image.** 
I could do it through the collate function on a normal PyTorch dataset, but I haven't found how to modify it using webdatasets. **Do you have any suggestions on how to do it?**

Thank you so much.

**Comment by henrique** [comment]
Hi @PardoAlejo 
if you were using webdataloader it was just a regular torch DataLoader (I think it was even removed from the last versions), so you can use any regular collate function there

**Comment by tmbdev** [comment]
Yes, @henrique is correct: whatever collate function you are using with DataLoader you can continue to use.

Also, keep in mind that pipeline stages are just simple iterators, so you can write any stream transformation you want to write:

```Python
def my_transformation(src):
    for sample in src:
        ...
        yield something
        ...

dataset = dataset.compose(my_transformation)
```

You can use conditionals, buffers, whatever you want inside your transformation. Your functions can collate, filter, insert samples, etc.
