### ISSUE TITLE
Include LICENSE file in PyPI builds

### ISSUE THREAD

**Issue by alhirzel** [webdataset/webdataset#229]
I am packaging `webdataset` on the Arch Linux AUR, and trying to follow [guidance for properly documenting the package license](https://wiki.archlinux.org/title/PKGBUILD#license). As part of this, it is best if I have access to a copy of the upstream `LICENSE` file. In the particular case of `webdataset`, this `LICENSE` file is not put into the PyPI package and is only present in the Git repository. I am trying to work directly from the PiPI package if possible.

Is it possible to put the `LICENSE` file in the PyPI wheels in the future?

**Comment by leng-yue** [comment]
I think you can make a pr to include that LICENSE file?

**Comment by tmbdev** [comment]
Done.

**Comment by alhirzel** [comment]
Thanks much :)
