### ISSUE TITLE
ShardList is not available

### ISSUE THREAD

**Issue by yncxcw** [webdataset/webdataset#230]
Hello,

Based on the doc [here](https://webdataset.github.io/webdataset/multinode/#splitting-shards-across-nodes-and-workers]). The preferred way to shard tar files cross nodes/workers is to use ShardList, but it seems that `ShardList` is not available in the latest version of WebDataset (0.2.30)

Thanks,

Wei

**Comment by tmbdev** [comment]
It's called SimpleShardList now. I have updated the documentation.
