### ISSUE TITLE
Automatic shard caching detects filename wrong with "s3cmd" in url, likely causing incorrect results

### ISSUE THREAD

**Issue by iceboundflame** [webdataset/webdataset#238]
Hi, I have found some strange behavior when using shard caching. My urls are as follows: `pipe:s3cmd get s3://bucket/path-{00008..00086}.tar -`. However, I notice that it only creates a single file in the `cache_dir`, named `s3cmd`. This seems like a serious problem, as it would mean that only one shard is being used!

Observed with `WDS_VERBOSE_CACHE=1`:

```
# downloading s3cmd to /data1/s3cmd
# downloading s3cmd to /data1/s3cmd
..
# opening /data1/s3cmd
# opening /data1/s3cmd
...
```

The bug could be here:

```
# webdataset/cache.py:
def pipe_cleaner(spec):
    """Guess the actual URL from a "pipe:" specification."""
    if spec.startswith("pipe:"):
        spec = spec[5:]
        words = spec.split(" ")
        for word in words:
            if re.match(r"^(https?|gs|ais|s3)", word):
                return word
    return spec
```

It appears to try and find the first word that starts with "s3" and use that. Clearly, "s3cmd" fits the bill. Same with "aws s3 cp" - it would match "s3". In general it seems like a risky proposition to try and clean the url, even if this is fixed, as other aspects of the string could also change the result. I suggest including a hash of the original full url.

**Comment by tmbdev** [comment]
I have added a small fix that should take care of this particular problem.

In general, it is convenient to have pipes mapped to the URLs they refer to heuristically.

You can always override the mapping by specifying the `url_to_name` option to `cached_url_opener`. I've added this option to the `WebDataset` wrapper class as well now.

**Comment by iceboundflame** [comment]
Thank you!

**Comment by drscotthawley** [comment]
Hi, just saw this Issue, and want to ask: How do we enable this caching for S3 urls?   The docs indicate the files are cached by default, but not sure if this applies to pipes.  Also, where does the cache go? e.g. I see this in the README...

> If you use the built-in caching mechanism, you can simply download shards to a local directory and specify that directory as the cache directory. 

How do we specify the cache directory?  I've searched through the documentation and the code (looking for "cache") but haven't yet found it.

**Comment by drscotthawley** [comment]
Can't find any mention of `cached_url_opener` [in the docs](https://webdataset.github.io/webdataset/search.html?q=cached_url_opener)

**Comment by drscotthawley** [comment]
@tmbdev I'm not sure if your fix is working.  Grabbing the latest `webdataset` from source, If I run...

```python
url = 'pipe:aws s3 --cli-connect-timeout 0 cp s3://s-laion-audio/webdataset_tar/FSD50K/test/0.tar -'
dataset = wds.WebDataset(url, cache_dir="./cache")
```
I get a directory in `./cache` that is simply named "`s3`".
