### ISSUE TITLE
Recommended way of mixing datasets?

### ISSUE THREAD

**Issue by gabrielilharco** [webdataset/webdataset#244]
What is the recommended way of combining multiple data sources, with a specified frequency for sampling from each? E.g. I want to combine shards `A/{00.99}.tar` with shards `B/{00.99}.tar`, but I wish to sample from `A` 1.45 times more frequently.
`MultiShardSample` seems close to this, but as I understand it it only supports integer weights (e.g. `resample=3`), is this right?

Any advice is greatly appreciated, thanks!

**Comment by tmbdev** [comment]
MultiShardSample is for mixing at the shard level. If you want to mix at the sample level, use RandomMix. Something like:

```
ds1 = WebDataset(...)
ds2 = WebDataset(...)
mix = RandomMix([ds1, ds2], [0.3, 0.7])
```

**Comment by frutiemax92** [comment]
How can you use RandomMix in a multiprocess/gpu setup? I have multiple tar files that I need to shuffle and dispatch the images across processes.
