### ISSUE TITLE
How to specify cache_dir for shard lists?

### ISSUE THREAD

**Issue by drscotthawley** [webdataset/webdataset#245]
I have a pipeline that looks like
```python
        dataset = wds.DataPipeline(
            wds.ResampledShards(urls),   #  cache_dir='./_mycache'), <-- cache_dir not allowed here
            wds.tarfile_to_samples(),
            wds.shuffle(shuffle_vals[0]),
            wds.decode(wds.torch_audio),
            wds.map(partial(callback, sample_size=sample_size, sample_rate=sample_rate, verbose=verbose, **kwargs)),
            wds.shuffle(shuffle_vals[1]),
            wds.to_tuple(audio_file_ext),
            wds.batched(batch_size),  
        ).with_epoch(epoch_len)
```
How do we turn on caching for lists of shards?  I'm not finding any automatic cache directory, and I unlike `wds.WebDataset`, `wds.ResampledShards` doesn't allow for a `cache_dir` kwarg.

**Comment by drscotthawley** [comment]
On further inspection, it seems ResampleShards grabs a bunch of shards, untars them all to memory; we train on that group of data for a while, then we throw it all away and get a bunch of new shards, and train on those,..

 
....and ResampleShards never checks to see if it's already downloaded a shard; 
the shard's files stay in memory until they're iterated-over but are then thrown away.  

I had imagined that it would cache some set of shards to the local disk to make re-loading faster, but no. 

Ready to close this Issue, I suppose.

**Comment by tmbdev** [comment]
`ResampledShards` performs statistical resampling, i.e. sampling with replacement. It's a valid way of sampling from the dataset and arguably a good data augmentation method.

However, the primary reason for ResampledShards is to allow large scale data parallel processing while guaranteeing equal number of batches on all nodes. It is not intended for improving caching (and will not meaningfully improve caching).

Caching works the same for ResampledShards as for any other shards: you need to replace `tarfile_to_samples` with `cached_tarfile_to_samples`.

Have a look at how the WebDataset wrapper constructs the pipeline:

https://github.com/webdataset/webdataset/blob/cb1aa32aca3f5fa3f214c38a2145b14cd28629cc/webdataset/compat.py#L97
