### ISSUE TITLE
Clarification on what `to_tuple()` does?

### ISSUE THREAD

**Issue by drscotthawley** [webdataset/webdataset#246]
Sorry I'm confused -- It's unclear from the documentation (and my reading of [the code](https://github.com/webdataset/webdataset/blob/cb1aa32aca3f5fa3f214c38a2145b14cd28629cc/webdataset/compat.py#L66) ) what the purpose of `.to_tuple()` is.  

It is used throughout the documentation (e.g., ["Getting Started"](https://webdataset.github.io/webdataset/gettingstarted/),  ["How it Works"](https://webdataset.github.io/webdataset/howitworks/#how-it-works)) and [README](https://github.com/webdataset/webdataset#readme) yet never described what it actually is or does.  It seems to be absolutely crucial since it appears in every example, but... what is it?   And how are we to learn which arguments to use with it? 

For example, what is the difference between `.to_tuple("png", "json")` and `.to_tuple("png;jpg;jpeg", "json")`?  Why is "json" the last argument?   

Does this mean that it's going to produce JSON text for the Python tuple `("png", "jpg", "jpeg")`?  Why would we want that -- is it that hard to simply write` '("png", "jpg", "jpeg")'`?

**Comment by tmbdev** [comment]
The `to_tuple` method extracts fields from a dictionary based on extension.

For example, for image classification training, you may have classes in .cls files and images in .png, .jpg, or .jpeg files. You would then write:

```
ds = WebDataset(...) ... .to_tuple("png;jpg;jpeg", "cls")
for image, cls in ds:

**Comment by cupdike** [comment]
Not a lot of direct experience here but maybe this will help...

Before you call `to_tuple`, the dataset is a dictionary coded using the keys you specified in your "sample" definition.  For example, this sample definition:
```
            sample = {
                    "__key__": str(sample_id),
                    'img': img,
                    'cls': cls
            }
```
 has this structure:
```
# grab a sample
>>> sample_dict = next(dataset.iterator())
>>> sample_dict.keys()
dict_keys(['__key__', '__url__', 'cls', 'img'])
```
So mapping this through using to_tuple:
```
>>> img, cls = next(dataset.to_tuple("img","cls").iterator())
>>> print(img[0:5])
b'\xff\xd8\xff\xe0\x00'
>>> print(cls)
b'1'
```
Presumably, your samples could use a mix of image file formats that changes from sample to sample. The arguments to to_tuple let you specify a list of possible format keys (delimited by ';'), and the first one found in the sample dictionary will be returned.  Hence the possible`.to_tuple("png;jpg;jpeg", "json")` invocation.  

It additionally appears that you can provide a single argument with a space separating the first tuple key(s) and the second tuple key.  That is, `.to_tuple("png;jpg;jpeg", "json")` is functionally equivalent to `.to_tuple("png;jpg;jpeg json")`.

**Comment by wtliao** [comment]
@cupdike Thanks for your very clear explanation. Now I am having a problem. In some of my .tar files have jpg, npy and txt files, but in some of them only  jpg and txt. Is there a way,  if jpg, npy and txt exist, read them all, if not, only read jpg and txt . something like

.decode("rgb").to_tuple('jpg','npy', 'txt')..map(preprocess)
....
def preprocess(sample):
image, masks, caption = sample
# if npy exists, masks read the npy file, if not, mask is None without raising error. 
Thanks!

**Comment by tmbdev** [comment]
Functions like `to_tuple` are just convenience functions that make the common cases quick and easy to write.

For anything complex, just use an explicit function:

```
def make_tuple(sample):
	return sample["jpg"], sample.get("npy"), sample["txt"]

ds = WebDatset(...) ... .map(make_tuple)
```
