### ISSUE TITLE
Nested tar support

### ISSUE THREAD

**Issue by kalyani7195** [webdataset/webdataset#247]
I was wondering if webdataset supports nested tar loading. So here's my usecase:
I have the following directory structure:
001.tar
--------123.tar
----------------img0.jpg
----------------img1.jpg
----------------img2.jpg
--------123.json

--------124.tar
----------------img0.jpg
----------------img1.jpg
----------------img2.jpg
--------124.json

--------125.tar
----------------img0.jpg
----------------img1.jpg
----------------img2.jpg
--------125.json

002.tar ...
003.tar ...

How should I load the images in the nested tar in this case?
Thanks!
Kalyani

**Comment by tmbdev** [comment]
You can just define your own decoder for .tar files using Python's tarfile library.

If you want to add the images to the sample as if they had been part of it all along, you can do this with a map:

```
def expand_tar_files(sample):
    stream = tarfile.open(fileobj=io.BytesIO(sample["tar"])
    for tarinfo in stream:
        name = tarinfo.name
        data = stream.extractfile(tarinfo).read()
        sample[name] = data

ds = WebDataset(...).map(expand_tar_files).decode(...)
```
