### ISSUE TITLE
password protection / encryption of files

### ISSUE THREAD

**Issue by ozanciga** [webdataset/webdataset#259]
is there a way to use password protected tars during streaming?

**Comment by tmbdev** [comment]
You can use arbitrary pipelines for reading, and you can put streaming decoders in there. So, just use as your data source:

```
urls = "pipe:curl -L -q https://storage.googleapis.com/bucket/shard-{000000..000999}.tar | gpg --decrypt -o - -"
dataset = WebDataset(urls).decode(...) etc.
```
