### ISSUE TITLE
Return filename in training loop

### ISSUE THREAD

**Issue by DonkeyShot21** [webdataset/webdataset#264]
Following up on this previous issue (https://github.com/webdataset/webdataset/issues/185), it is still unclear how to return the file name in the training loop. I have a pipeline similar to [open-clip](https://github.com/mlfoundations/open_clip) where i return images, captions and metadata:

```
pipeline = [
    wds.SimpleShardList(input_shards),
    wds.split_by_worker,
    wds.tarfile_to_samples(handler=log_and_continue),
    wds.select(filter_no_caption_or_no_image),
    wds.decode("pilrgb", handler=log_and_continue),
    wds.rename(image="jpg;png;jpeg;webp", text="txt", metadata="json"),
    wds.map_dict(
        image=preprocess_img,
        text=lambda text: tokenizer(text),
        metadata=lambda x: x,
    ),
    wds.to_tuple("image", "text", "metadata"),
    wds.batched(args.batch_size, partial=not is_train),
]
```
I would like my `metadata` dict to also contain the file name (only the stem, not the extension). How do I do that?

**Comment by tmbdev** [comment]
The file name (without the extension) within the tar file name is always in sample["__key__"]. The source data for sample["image.jpg"] is found in the file named `sample["__key__"] + "." + "image.jpg"` inside the .tar file.

The tar file name itself is in sample["__url__"]
