### ISSUE TITLE
Online transformations

### ISSUE THREAD

**Issue by richdsmith** [webdataset/webdataset#266]
As far as I can tell, the transformations are applied immediately via `Webdataset(url)....map(func)`

Our current workflow operates under the assumption that for each epoch images will get different transformations to maximise the visual variety of training data. 

Is there a way to defer the transformations until a batch is fetched? Or desire for this? Should I just be reloading the dataset from scratch for each epoch?

**Comment by tmbdev** [comment]
I'm not exactly sure what you mean. WebDataset doesn't apply transformations immediately. Rather, it constructs a pipeline through which data flows.

In other words, the dataset is "loaded from scratch" during each epoch by default, including running through the entire processing pipeline.

The above code will invoke `func` again for each sample during each epoch, so if `func` uses some random number generator, the transformed image will be different during each epoch.

(If you actually do want to process the dataset only once, use the ".lmdb_cached" functionality after your data augmentation and cache the transformed images locally.)
