### ISSUE TITLE
ShardWriter does not properly close tar files

### ISSUE THREAD

**Issue by voegtlel** [webdataset/webdataset#274]
Hi There,

I'm getting lots of warning in my tests, that the tar writer has "unclosed files" when using `ShardWriter` and found this:

[webdataset/writer.py](https://github.com/webdataset/webdataset/blob/faa774ec4e81cb738a4911691c59b68829505a2a/webdataset/writer.py#LL417C1-L418C54)

```python
        stream = open(self.fname, "wb")
        self.tarstream = TarWriter(stream, **self.kw)
```

which will set the `own_fileobj` of `TarWriter` to `None`, because it is passed as already opened handle. I wonder, is there a reason for this explicit behavior, or is it a bug? (it seems so explicitly intended)

If a bug, this should probably read:
```python
        self.tarstream = TarWriter(self.fname, **self.kw)
```

Thanks!

**Comment by justinpinkney** [comment]
This would also address #216
