### ISSUE TITLE
Is it possible to add parameters like fps to wds.torch_video

### ISSUE THREAD

**Issue by FingerRec** [webdataset/webdataset#277]
Thanks for your good work.

For wds, the default way to load video is wds.torch_video.

However, I find it require huge memory. Is it possible to call wds.torch_video with param like fps, begin_time, end_time?

**Comment by tmbdev** [comment]
I'd recommend handling any complex video decoding tasks via an explicit function. You can use either `map` or `compose`.

```
def decode_video(sample):
    raw = sample["mp4"]
	...
    sample["mp4"] = decoded
dataset = dataset.map(decode_video).decode("rgb")
```

Note that you want the `decode` method after the `map` method.

Often, you have long videos and you actually want to generate samples from them. You might do something like:

```
def expand_video(sample):
	for frame in frames_of(sample["mp4"]):
        result = dict(sample)
        del result["mp4"]
        result["img"] = frame
        yield result

dataset = dataset.compose(expand_video).decode("rgb")
```

This will turn each frame in the video into an individual sample. You can write slightly more complex code to return, say, triples of consecutive frames. You probably want to shuffle both within the dataset and across multiple workers for code like this.
