### ISSUE TITLE
Why with_epoch(N) needed for multinode training?

### ISSUE THREAD

**Issue by inkzk** [webdataset/webdataset#278]
2 speculation need to be verified:
1. Is ending one epoch after N batches the only reason of `with_epoch(N)` ? Without that, the epoch will continue infinitly under the "infinite stream of samples" of webdataset.
2. Different from `sampler` of `pytorch Dataloader`, `set_epoch` is not needed in webdatset?

**Comment by tmbdev** [comment]
WebDataset is agnostic about how you handle epochs or whether you use epochs at all.

If you choose resampling, WebDataset generates an infinite stream of samples, and in that case, if your code expects epochs, `with_epoch` is a useful tool to use.

WebDataset uses the IterableDataset interface; `set_epoch` simply isn't supported under that interface at all. So, in that sense, it is not needed.
