### ISSUE TITLE
Problem with readme.ipynb ?

### ISSUE THREAD

**Issue by gui-miotto** [webdataset/webdataset#280]
The section about the Pipeline Interface In the `readme.ipynb` shows the following code:

``` python
dataset = wds.DataPipeline(
    wds.SimpleShardList(url),
    # at this point we have an iterator over all the shards
    wds.shuffle(100),
    wds.split_by_worker,
    # at this point, we have an iterator over the shards assigned to each worker
    wds.tarfile_to_samples(),
    wds.shuffle(1000),
    wds.decode("torchrgb"),
    # at this point, we have an list of decompressed training samples from each shard in this worker in sequence
    get_patches,  # note that can put iterator->iterator functions into the pipeline directly
    wds.shuffle(10000),
    wds.to_tuple("big.jpg", "json"),
    wds.batched(16)
)

batch = next(iter(loader))
batch[0].shape, batch[1].shape
```
Output: `(torch.Size([12, 256, 256, 3]), torch.Size([12]))`

But I think the line before the last should actually be:

```python
batch = next(iter(dataset))  # not loader, but dataset
```
And the expected cell output should be: `(torch.Size([16, 256, 256, 3]), torch.Size([16]))`

(Batch size should be 16 instead of 12)

However, just replacing `loader` by `dataset` will not work, because I think the pipeline order is not correct. This haven't been spotted before because the dataset was indeed never used.

I'm very new to the package, but I'll try to fix this anyway. Meanwhile, maybe someone could tell me if I'm correct about this issue.

Best,
Gui

**Comment by tmbdev** [comment]
Thanks for spotting this; I'll fix it.
