### ISSUE TITLE
Providing credentials for reading objects from a private bucket

### ISSUE THREAD

**Issue by stwerner97** [webdataset/webdataset#283]
Hi, thanks for the amazing work on ``webdataset``! 😊 

I want to load a ``webdataset`` from a non-publicly accessible bucket. How can I provide the ``access key id`` and ``secret access key`` to authenticate my requests?

Also, I am using a provider other than AWS or GCS, i.e., NetApp.

**Comment by tmbdev** [comment]
WebDataset just uses command line programs, so you provide credentials in whatever way you provide credentials to them.

For builtin protocols like "gs:", WebDataset invokes "gsutil ...", so if "gsutil ..." works from the command line, it works in WebDataset.

For more complex I/O needs, you can use "pipe:command ..." as your URL. Here, "command..." can be any kind of shell command line to read a shard. For complex needs, just use a script as your command. Brace expansion still happens as for all other URLs.

**Comment by stwerner97** [comment]
Thanks so much! 👍
