### ISSUE TITLE
Support for interleaved dataset

### ISSUE THREAD

**Issue by RunpeiDong** [webdataset/webdataset#289]
Hi,

Is it possible that the webdataset could support interleaved datasets such as MMC4? In this case, one example may have a text list with several images instead of only one image.

Regards

**Comment by DreamLLM** [comment]
I have implemented by myself, I will try to make a PR when I have time.

**Comment by tmbdev** [comment]
You can represent this the same way you would do on a file system. An easy way to do this would be to put the hierarchical structure into a .Json file that references image files, and the put the image files into the same sample.
