### ISSUE TITLE
How to skip a sample if decoding fails? 

### ISSUE THREAD

**Issue by juliawilkins** [webdataset/webdataset#291]
If something fails in the decoding of a sample (i.e. image decoding, due to possibly a corrupt image), is there a way to skip a sample? The closest thing I could find with with nvidia dali here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_webdataset.html with their `missing_component_behavior` parameter.  Thank you!

**Comment by fabito** [comment]
You can pass the handler parameter (i.e. `warn_and_continue`) when invoking  `.map`, `.map_tuple` or `.decode` etc

```python
    ds = (
        wds.WebDataset(
            url, handler=warn_and_continue, shardshuffle=True, verbose=verbose)
        .map(_mapper, handler=warn_and_continue)
        .to_tuple("jpg", "cls")
        .map_tuple(transform, identity, handler=warn_and_continue)
        .batched(batch_size)
    )
```
