### ISSUE TITLE
`to_tuple()` needs **kwargs as well.

### ISSUE THREAD

**Issue by delta-func** [webdataset/webdataset#304]
In the `FluidInterface` implementation of `to_tuple()`

https://github.com/webdataset/webdataset/blob/b092eb6617e090b3e5261ab60e12b263bc107f51/webdataset/compat.py#L55-L56

`**kwargs` also needs to be handed over to `filters.to_tuple` to use e.g., `missing_is_error=False`, but currently not.

It seems this has been fixed in the old version via https://github.com/webdataset/webdataset/pull/87/files, but removed in the current version.

**Comment by sdebnathusc** [comment]
@tmbdev I am also running into this issue and would want to have the flexibility to set `missing_is_error=False`. Will really appreciate if this issue gets fixed.

**Comment by tmbdev** [comment]
Fixed.
