### ISSUE TITLE
Functionality to split a WDS

### ISSUE THREAD

**Issue by floschne** [webdataset/webdataset#313]
Hi and first of all thanks for this amazing work!

In my scenario I have a small (500K) text-image pair dataset in form of a WDS stored in an external storage container that I can mount in my system, i.e., I use a local path to instantiate the WDS.

My question now is, if there is a way to split the WDS into train, test, and validation without "manual extract/move/compress" work?

Thanks in advance!

**Comment by floschne** [comment]
> Have you checked `tarp` ([this video](https://www.youtube.com/watch?v=kIv8zDpRUec) is a good resource) ?

I tried to do it with `tarp` but the video doesn't really cover my use case and it's too time-consuming to read through the source code to understand it 🙈

**Comment by tmbdev** [comment]
Hi! Sorry about the incomplete documentation for `tarp`. 

Generally, the simplest for Python programmers is probably just to write a small Python program for doing such transformations:

```
for shard in shards:
	src = WebDataset(shard)
   dst = TarWriter(output_shard)
   for sample in src:
      if ...: continue  # skip samples you don't want
      dst.write(sample)
```

For more complex operations, parallel and distributed transformations, shuffling, and sorting, the recommended library to use is Ray.  There is code in the ./examples directory that illustrates how to do this.
