### ISSUE TITLE
Standardization of more elaborate, hierarchical grouping schemes (multiple frames, object masks, etc)

### ISSUE THREAD

**Issue by rwightman** [webdataset/webdataset#319]
I've run into a few scenarios over usage of webdataset where more elaborate grouping schemes is useful. A few particular scenarios. 

1. Multi-frame samples, where each sample consists of multiple individual files of the same type (and a video container format isn't convenient / appropriate). 
    - sets of jpg frames with different timestamps (short sequence)
    - sets of sensor captures of same encoded file type for different views, different wavelengths, etc (ie png for different bands of satellite + RGB + ...)

2. Object image datasets where there could be multiplicity of supporting files for the main image sample, needing to be matched to other metadata (ie obj annotations in json)
    - an image frame with a set of binary / png masks for each object instance in the frame, another png for semantic segmentation, etc
  
Illustrated are some hypothetical sample dicts with a hierarchy represent this, 

```
sample_0.frames.0.jpg
sample_0.frames.0.timestamp
sample_0.frames.1.jpg
sample_0.frames.1.timestamp
sample_0.frames.2.jpg
sample_0.frames.2.timestamp
sample_0.duration
sample_0.json

img_seq_sample = {    
    '__key__': 'sample_0',
    'frames': {
        "0": {
            "jpg": Image(),
            "timestamp": 10001,
        },
        "1": {
            "jpg": Image(),
            "timestamp": 10002,
        },
        "2": {
            "jpg": Image(),
            "timestamp": 10003,
        }
    },
    'json': {},
    'duration': 3
}
```

```
sample_0.jpg
sample_0.masks.obj_a.png
sample_0.masks.obj_b.png
sample_0.json

obj_detect_sample = {    
    '__key__': 'sample_0',
    'jpg': Image(),
    'masks': {
        "obj_a": {
            "png": Mask(),
        },
        "obj_b": {
            "png": Mask(),
        },
    },
    'json': {
        'bbox': [[0,0,10,10], [5,5,20,20]],
        'category_id': [0, 1]
    },
}
```

The default key/grouping scheme splits at the first '.' so you can get unique suffixes for all of the above, but it's flat, and with the open set nature of sequences, you'd have to go a bit crazy with mappings on decoders, etc to get something reasonable from it.

I'm curious if you've had any ideas on this yourself @tmbdev, if you're open to having more standardizes schemes available as alternate grouping/key fns in the library (vs them being maintained outside the core library)...

**Comment by tmbdev** [comment]
The naming scheme you are using is perfectly fine, and it defines a hierarchy using "." separators. You can also use separators other than "." and "/" to define your hierarchy between the first and last dot in the file name.

Ultimately, WebDataset needs to decide what set of files to load at once as a sample. It also needs to decide what set of files it needs to keep together during shuffle operations. The naming conventions it has support this fairly well and naturally for most datasets.

I agree that it "feels a little odd" to build hierarchies like "sample.frame.1.jpg" and "sample.frame.2.jpg", but if we used "/" for expressing these hierarchies, the simpler use case would be more complex.

For complex structures, it's easiest not to worry about expressing the hierarchies in the file names anyway; just number the files sequentially and then express the structure in your JSON file explicitly:

```
sample_0.000.jpg
sample_0.001.jpg
sample_0.002.jpg```
sample_0.json
```

where your JSON contains:

```
{
    "frames": ["000.jpg", "001.jpg", "002.jpg"],
    "timestamps": [...],
    "duration": ...
}
```
