### ISSUE TITLE
100% CPU load whilst specifying only 1/3rd of the available cores

### ISSUE THREAD

**Issue by floschne** [webdataset/webdataset#321]
Hi :)

I've a question regarding the `num_workers` parameter. I'm running code to train a model using webdataset and lightning on a 96 cores machine and I'm specifying `num_workers=32`  for  my `wds.WebLoader` dataloader. However, the code consumes 100% of CPU resources. 

Is this a problem of webdataset or lightning? Did somebody experience the same or similar behavior?

**Comment by tmbdev** [comment]
WebDataset doesn't use any threading and hardly uses any computation. Most likely, you are running some multithreaded code inside your dataloaders, and that code may use many threads at once. You might need to set OMP_NUM_THREADS or MKL_NUM_THREADS, for example.
