### ISSUE TITLE
Slow loading speed with huggingface trainer

### ISSUE THREAD

**Issue by xipq** [webdataset/webdataset#324]
I implement a simple data pipeline when loading a caption dataset:
```
pipeline_wds_dataset = wds.DataPipeline(
    wds.ResampledShards(url),
    wds.tarfile_to_samples(),
    wds.decode("pil"),
    wds.to_tuple("txt", "jpg", "__key__"),
    wds.map(image_processor),                          # image processor that crops and transforms the image
    wds.batched(batch_size, collation_fn=collator),    # collator, including tokenizing the text
)
```
When I load and iter the dataset with an ordinaty pytorch dataloader (512 batch size, 8 cards), the performance is desiable (~2 it/s). However, when I pass the dataset to Huggingface's trainer (together with a by-pass collator and batch_size=1 for huggingface) and train using DDP, the data loading speed seems to be very slow. It hangs for a huge amount of time between every step (>30s).

Also, tuning up `num_workers` is helpful for improving speed when using pytorch dataloader, but it seems not working well for huggingface trainer (changing the `dataloader_num_workers` correspondingly).

I would like to know that whether the issue arises from my current implementation, or from compability? Thanks for any advice~

**Comment by Guptajakala** [comment]
@xipq could you share how you solved the problem?

**Comment by xipq** [comment]
> @xipq could you share how you solved the problem?

Also use the data collator from webdatasets instead of the default one. You may implement `get_train_dataloader` in your custom trainer.

**Comment by xipq** [comment]
> @xipq could you share how you solved the problem?

My implementation looks like

```python
 def get_train_dataloader(self) -> DataLoader:
        """
        override and use webdatasets as dataloader
        """
        import webdataset as wds

        if self.train_dataset is None:
            raise ValueError("Trainer: training requires a train_dataset.")

        train_dataset = self.train_dataset
        data_collator = self.data_collator

        dataloader = wds.WebLoader(
            train_dataset,
            batch_size=None,
            shuffle=False,
            num_workers=self.args.dataloader_num_workers,
            persistent_workers=self.args.dataloader_num_workers > 0,
        )

        return self.accelerator.prepare(dataloader)
```
