### ISSUE TITLE
BUG: ValueError when missing_is_Error=True

### ISSUE THREAD

**Issue by iraj465** [webdataset/webdataset#328]
I have webdataset tar with following format during write:
`{

                "__key__": "%07d" % idx,
                "model_input.pyd": torch.load(os.path.join(path1, "model_input", row.image_hash + ".pt"), map_location=torch.device('cpu')),
                "crop_top_lefts.pyd": torch.load(os.path.join(path1, "crop_top_lefts", row.image_hash + ".pt"), map_location=torch.device('cpu')),
                "original_sizes.pyd": torch.load(os.path.join(path1, "original_sizes", row.image_hash + ".pt"), map_location=torch.device('cpu')),
                "pooled_prompt_embeds.pyd": torch.load(os.path.join(path2, "pooled_prompt_embeds", row.title_hash + ".pt"), map_location=torch.device('cpu')),
                "prompt_embeds.pyd": torch.load(os.path.join(path2, "prompt_embeds", row.title_hash + ".pt"), map_location=torch.device('cpu')),
        
}
`

Now when loading to tuples with filter key like this:
`

        
        processing_pipeline = [
            wds.decode("torch",handler=wds.ignore_and_continue),
          wds.map(filter_keys({"model_input.pyd","crop_top_lefts.pyd","original_sizes.pyd","pooled_prompt_embeds.pyd","prompt_embeds.pyd"})),
            wds.to_tuple("model_input.pyd","crop_top_lefts.pyd","original_sizes.pyd","pooled_prompt_embeds.pyd","prompt_embeds.pyd"),
        ]
`

Getting error:
`
  File "/opt/saptarshi.majumder/catalog.Linux_debian_11.py38.hfd0/lib/python3.8/site-packages/webdataset/filters.py", line 125, in getfirst
    raise ValueError(f"didn't find {keys} in {list(a.keys())}")
ValueError: didn't find ['model_input.pyd'] in ['crop_top_lefts.pyd', '__key__']
`
What could be the reason for this error and how to mitigate this? Any help is appreciated

**Comment by tmbdev** [comment]
Well, it tells you: the only keys it finds in the sample after `filter_keys` is `crop_top_lefts.pyd`; `model_input.pyd` just isn't present anymore:

```
didn't find {keys} in {list(a.keys())}") ValueError: didn't find ['model_input.pyd'] in ['crop_top_lefts.pyd', '__key__']
```

You don't have to filter out unused keys before to_tuple anyway.

I recommend writing more complex processing pipelines like this simply as mapping functions. You can write the transformation into tuples like this and use `.map(prepare)`:

```
def prepare(sample):
	return (
		sample["model_input.pyd"],
		sample["crop_top_lefts.pyd"],
		sample["original_sizes.pyd"],
		sample["pooled_prompt_embeds.pyd"],
		sample["prompt_embeds.pyd"]
    )
```

But you probably actually want to do even more preprocessing in the `prepare` function and generate your actual tensors there.

`to_tuple` is mainly intended for very simple extraction of features that are then directly handed off to a training loop.
