### ISSUE TITLE
How to create the wds json file for wids

### ISSUE THREAD

**Issue by NIRVANALAN** [webdataset/webdataset#329]
Hi, thanks for the new wids interface. Since wids relies on a pre-defined metafile for random access (like https://github.com/webdataset/webdataset/blob/11e6b623a071ef44fbbde02b7a1639d3f25f61a2/tests/test_wids.py#L186 and train_url = "https://storage.googleapis.com/webdataset/fake-imagenet/imagenet-train.json"), I wonder whether there is any official documents to create such json file from an off-the-shelf wds shards dataset?

Thanks!

**Comment by faradayin** [comment]
Hi, there ! I wonder this question too. And I generated a json file by myself, according to the example json file : https://[storage.googleapis.com/webdataset/fake-imagenet/imagenet-train.json](https://storage.googleapis.com/webdataset/fake-imagenet/imagenet-train.json)

it seems to work fine. Although I'm not sure if it is really ok.

**Comment by NIRVANALAN** [comment]
Thanks Like, I'll check it out!

**Comment by tmbdev** [comment]
The webdataset distribution installs a command called `widsindex`. It takes a list of shards/shardspecs and creates an index for it.

**Comment by v-iashin** [comment]
thanks for making this tool! 

one nit: the faq is missing the first argument that `widsindex` wants. if you run it as the faq suggests, it will complain:

```
widsindex: error: argument command: invalid choice: 'train-00000.tar' (choose from 'create', 'update', 'info', 'sample')
```
