### ISSUE TITLE
Handling multiple annotations per image

### ISSUE THREAD

**Issue by uehara-mech** [webdataset/webdataset#334]
I'm working with a dataset where each image is associated with a variable number of annotations, and I'm seeking advice on the best way to handle this with webdataset.
For instance, I have images like `1.jpg` that are associated with multiple captions, such as `1.txt`, `2.txt`, ..., `5.txt`.
Not all images have the same number of captions; the number of captions per image varies across the dataset.

From my understanding, webdataset primarily handles data where there's a one-to-one correspondence between images and annotations.

As discussed in #91 , one might use a function like this to expand multiple captions for a single image:

```python
def expand_captions(src):
    for image, captions in src:
        for c in captions.strip().split("\n"):
            yield image, c
```
And then use it as follows:
```python
ds = WebDataset(...).to_tuple("png", "captions").decode(...).then(expand_captions).shuffle(10000)
```

However, I'm concerned that this approach won't fully shuffle the dataset; annotations for the same image might only appear in close iterations, not fully mixed throughout the dataset.

Moreover, I would like to avoid flattening the dataset in advance to prevent storage capacity issues.

Are there any recommended practices on how to handle datasets with a variable number of annotations per image while still ensuring thorough shuffling of the dataset?

**Comment by tmbdev** [comment]
There are many different ways you can handle this. 

# WebDataset

Here is just one idea: store the image as `sample.jpg` and the annotations in JSON format as `sample.json`. Then just map  the sample with:

```
def transform_sample(sample):
	annotations  = sample["json"]["annotations"]
	sample["annotation"] = annotations[random.randrange(len(annotations))]
```

If you want to ensure that annotations are encountered regularly, you can also use:

```
def transform_sample(sample):
	epoch = sample["__epoch__"]
	annotations  = sample["json"]["annotations"]
	sample["annotation"] = annotations[epoch % len(annotations)]
```

# WIDS

You can use the same approaches above also with WIDS.

WIDS also gives you the option of training on an exact full permutation of all (image, annotation) pairs. You can use whatever approach you use with a regular indexed dataset and use WIDS. Presumably, you would start with computing a list of all the (image, annotation) pairs, then permute them.

```
pairs = []
for i in range(len(dataset)):
	for j in range(len(dataset[i]["annotations"])):
		pairs.append((i, j))
```

This will not usually give you better results, but it is a lot more complicated to implement. But, again, that's the same whether you use WIDS or any other indexed dataset. I would recommend the very first approach suggested above  instead.
