### ISSUE TITLE
slow data loading speed

### ISSUE THREAD

**Issue by 285220927** [webdataset/webdataset#339]
webdataset==0.2.86

When I use webdataset, it loads the dataset slower than pytorch, even if I use a local dataset

``` python
import torch
from torchvision import transforms
from tqdm import tqdm
import webdataset as wds
import torchvision.datasets as datasets


transform = transforms.Compose([
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])


def ds():
    dataset = datasets.ImageFolder('/path/dataset', transform)
    dataloader = torch.utils.data.DataLoader(dataset, num_workers=4, batch_size=256)
    for index, data in tqdm(enumerate(dataloader)):
        # 136it [00:35,  3.80it/s]
        pass


def webds():
    dataset = (
        wds.WebDataset('file:///path/dataset.tar')
            .decode("pil")
            .to_tuple("jpg;png;jpeg cls")
            .map_tuple(transform, lambda x: x)
    )
    dataloader = wds.WebLoader(dataset, num_workers=4, batch_size=256)
    for index, data in tqdm(enumerate(dataloader)):
        # 30it [00:35,  1.19s/it]
        # using HTTP here is even slower
        pass
```
I woule like to know if my usage is incorrect, thanks for any advice

**Comment by HuangChiEn** [comment]
> webdataset==0.2.86
> 
> When I use webdataset, it loads the dataset slower than pytorch, even if I use a local dataset
> 
> ```python
> import torch
> from torchvision import transforms
> from tqdm import tqdm
> import webdataset as wds
> import torchvision.datasets as datasets
> 
> 
> transform = transforms.Compose([
>     transforms.RandomResizedCrop(224),
>     transforms.RandomHorizontalFlip(),
>     transforms.ToTensor(),
>     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
> ])
> 
> 
> def ds():
>     dataset = datasets.ImageFolder('/path/dataset', transform)
>     dataloader = torch.utils.data.DataLoader(dataset, num_workers=4, batch_size=256)
>     for index, data in tqdm(enumerate(dataloader)):
>         # 136it [00:35,  3.80it/s]
>         pass
> 
> 
> def webds():
>     dataset = (
>         wds.WebDataset('file:///path/dataset.tar')
>             .decode("pil")
>             .to_tuple("jpg;png;jpeg cls")
>             .map_tuple(transform, lambda x: x)
>     )
>     dataloader = wds.WebLoader(dataset, num_workers=4, batch_size=256)
>     for index, data in tqdm(enumerate(dataloader)):
>         # 30it [00:35,  1.19s/it]
>         # using HTTP here is even slower
>         pass
> ```
> 
> I woule like to know if my usage is incorrect, thanks for any advice

hello, could you share how you solve it ?

**Comment by 285220927** [comment]
> > webdataset==0.2.86
> > When I use webdataset, it loads the dataset slower than pytorch, even if I use a local dataset
> > ```python
> > import torch
> > from torchvision import transforms
> > from tqdm import tqdm
> > import webdataset as wds
> > import torchvision.datasets as datasets
> > 
> > 
> > transform = transforms.Compose([
> >     transforms.RandomResizedCrop(224),
> >     transforms.RandomHorizontalFlip(),
> >     transforms.ToTensor(),
> >     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
> > ])
> > 
> > 
> > def ds():
> >     dataset = datasets.ImageFolder('/path/dataset', transform)
> >     dataloader = torch.utils.data.DataLoader(dataset, num_workers=4, batch_size=256)
> >     for index, data in tqdm(enumerate(dataloader)):
> >         # 136it [00:35,  3.80it/s]
> >         pass
> > 
> > 
> > def webds():
> >     dataset = (
> >         wds.WebDataset('file:///path/dataset.tar')
> >             .decode("pil")
> >             .to_tuple("jpg;png;jpeg cls")
> >             .map_tuple(transform, lambda x: x)
> >     )
> >     dataloader = wds.WebLoader(dataset, num_workers=4, batch_size=256)
> >     for index, data in tqdm(enumerate(dataloader)):
> >         # 30it [00:35,  1.19s/it]
> >         # using HTTP here is even slower
> >         pass
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I woule like to know if my usage is incorrect, thanks for any advice
> 
> hello, could you share how you solve it ?

Replace
`wds.WebDataset('url1')`
with
`wds.WebDataset(['url1', 'url2', 'url3', 'url4'])`
Through my testing, I found that the __init__ function of WebDataset can accept a list of URLs. Ensure that the number of URLs in the list is not less than the number of workers. I speculate that the reason could be that multiple workers reading data from multiple URLs might be faster than multiple workers reading data from a single URL.

**Comment by HuangChiEn** [comment]
> > > webdataset==0.2.86
> > > When I use webdataset, it loads the dataset slower than pytorch, even if I use a local dataset
> > > ```python
> > > import torch
> > > from torchvision import transforms
> > > from tqdm import tqdm
> > > import webdataset as wds
> > > import torchvision.datasets as datasets
> > > 
> > > 
> > > transform = transforms.Compose([
> > >     transforms.RandomResizedCrop(224),
> > >     transforms.RandomHorizontalFlip(),
> > >     transforms.ToTensor(),
> > >     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
> > > ])
> > > 
> > > 
> > > def ds():
> > >     dataset = datasets.ImageFolder('/path/dataset', transform)
> > >     dataloader = torch.utils.data.DataLoader(dataset, num_workers=4, batch_size=256)
> > >     for index, data in tqdm(enumerate(dataloader)):
> > >         # 136it [00:35,  3.80it/s]
> > >         pass
> > > 
> > > 
> > > def webds():
> > >     dataset = (
> > >         wds.WebDataset('file:///path/dataset.tar')
> > >             .decode("pil")
> > >             .to_tuple("jpg;png;jpeg cls")
> > >             .map_tuple(transform, lambda x: x)
> > >     )
> > >     dataloader = wds.WebLoader(dataset, num_workers=4, batch_size=256)
> > >     for index, data in tqdm(enumerate(dataloader)):
> > >         # 30it [00:35,  1.19s/it]
> > >         # using HTTP here is even slower
> > >         pass
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I woule like to know if my usage is incorrect, thanks for any advice
> > 
> > 
> > hello, could you share how you solve it ?
> 
> Replace `wds.WebDataset('url1')` with `wds.WebDataset(['url1', 'url2', 'url3', 'url4'])` Through my testing, I found that the `__init__` function of WebDataset can accept a list of URLs. Ensure that the number of URLs in the list is not less than the `num_workers` parameter. I speculate that the reason could be that multiple workers reading data from multiple URLs might be faster than multiple workers reading data from a single URL.

wow, thanks for your reply!!
