### ISSUE TITLE
The behavior of one node multi-gpus with webdataset

### ISSUE THREAD

**Issue by HuangChiEn** [webdataset/webdataset#341]
Hello, this issue just want to clarify the concept of the behavior of one node multi-gpus with webdataset (in torchlightning + DDP strategy). According to several test i run, I can not let 2 gpus take the shard data from the "identical dataset".
Suppose I have 200 shard data, how to setup webdataset or torch.utils.DataLoader, so that 2 gpus share with 200 shard data (per gpus only take 100 shard for each epoch ?) ?

( In torchlightning, we let Lightningmodule handle the  DDP strategy. So we're also not sure webdataset can realize the num_gpus and correct its behavior.

**Comment by tmbdev** [comment]
I'm not sure what you're asking.

For splitting, you have two options: webdataset and wids.

# webdataset

You can specify any nodesplitter you like to split shards among nodes. You can do this as an argument to the `WebDataset` class, or you can do it explicitly, since `WebDataset` is just a wrapper for `DataPipeline`:

````
    dataset = wds.DataPipeline(
        wds.SimpleShardList(list(map(str, range(10)))),
        wds.split_by_node,
        wds.split_by_worker,
        wds.non_empty,
	    ...
    )
```

# wids

In the `wids` library, you don't have explicit access to shards; everything is specified by index. If you want to ensure that each GPU only sees a subset of the shards, you need to arrange for the sampler you use to do that. Look at `DistributedChunkedSampler` on how to use rank and worker arguments to choose a subset of the indexes.

**Comment by HuangChiEn** [comment]
> I'm not sure what you're asking.
> 
> For splitting, you have two options: webdataset and wids.
> 
> # webdataset
> You can specify any nodesplitter you like to split shards among nodes. You can do this as an argument to the `WebDataset` class, or you can do it explicitly, since `WebDataset` is just a wrapper for `DataPipeline`:
> 
> ```
>     dataset = wds.DataPipeline(
>         wds.SimpleShardList(list(map(str, range(10)))),
>         wds.split_by_node,
>         wds.split_by_worker,
>         wds.non_empty,
> 	    ...
>     )
> ```
> 
> # wids
> In the `wids` library, you don't have explicit access to shards; everything is specified by index. If you want to ensure that each GPU only sees a subset of the shards, you need to arrange for the sampler you use to do that. Look at `DistributedChunkedSampler` on how to use rank and worker arguments to choose a subset of the indexes.
> 
> I haven't tried `wids` with Lightning, but you should be able to use it directly, since it is just a regular indexed dataset.

webdataset solution looks good, but I have the following form :
```
pair_ds = wds.WebDataset(str(shard_path), resampled=True).decode('pilrgb', handler=wds.warn_and_continue).to_tuple("jpg", "txt", handler=wds.warn_and_continue)
```

Is there a way to add `wds.split_by_node`, `wds.split_by_worker` in `pair_ds` ?

**Comment by HuangChiEn** [comment]
> I'm not sure what you're asking.
> 
> For splitting, you have two options: webdataset and wids.
> 
> # webdataset
> You can specify any nodesplitter you like to split shards among nodes. You can do this as an argument to the `WebDataset` class, or you can do it explicitly, since `WebDataset` is just a wrapper for `DataPipeline`:
> 
> ```
>     dataset = wds.DataPipeline(
>         wds.SimpleShardList(list(map(str, range(10)))),
>         wds.split_by_node,
>         wds.split_by_worker,
>         wds.non_empty,
> 	    ...
>     )
> ```
> 
> # wids
> In the `wids` library, you don't have explicit access to shards; everything is specified by index. If you want to ensure that each GPU only sees a subset of the shards, you need to arrange for the sampler you use to do that. Look at `DistributedChunkedSampler` on how to use rank and worker arguments to choose a subset of the indexes.
> 
> I haven't tried `wids` with Lightning, but you should be able to use it directly, since it is just a regular indexed dataset.

Yes, `You can specify any nodesplitter you like to split shards among nodes.` is what I'm trying to do. But, it got stuck with training in torchlightning.

I have tried 2 kind of method : 
(1) official website pipeline API
```
dataset = wds.DataPipeline(
    wds.SimpleShardList(urls),

    # at this point we have an iterator over all the shards
    wds.shuffle(100),

    # add wds.split_by_node here if you are using multiple nodes
    wds.split_by_node,    
    wds.split_by_worker,

    # at this point, we have an iterator over the shards assigned to each worker
    wds.tarfile_to_samples(),

    # this shuffles the samples in memory
    wds.shuffle(1000),

    # this decodes the images and json
    wds.decode("pil"),
    wds.to_tuple("png", "json"),
    wds.map(preprocess),
    wds.shuffle(1000),
    wds.batched(16)
)
```

(2) There're a japanes ninja give a clear example similar with your method, but it still got stuck..
```
class Liaon115M(pl.LightningDataModule):
    ...
    def setup(...):
        def wrap_wds(shard_path, ratio):
            trfs = lambda tup : (self.img_transforms(tup[0]), self.txt_transforms(tup[1])) 
            raw_web_ds = wds.WebDataset(str(shard_path), nodesplitter=wds.split_by_node)
            # I have set `handler=wds.warn_and_continue` in decode & to_tuple, but it's not stuck in here...
            pair_ds = raw_web_ds.decode('pilrgb').to_tuple("jpg", "txt")
            return pair_ds.batched(self.batch_size, partial=False)
        self.train_ds = wrap_ds(...)

    def train_dataloader(self):
        sample_loader = wds.WebLoader(
            self.train_ds, 
            batch_size=None, 
            shuffle=False,   
            pin_memory=True, 
            num_workers=self.num_workers
        )
        dataset_size = self.total_num_ds * self.split_ratio[0]
        num_batches = int( dataset_size // (self.batch_size * self.n_gpu) )

        sample_loader.length = num_batches
        sample_loader = sample_loader.with_length(num_batches)

        sample_loader = sample_loader.repeat(nbatches=num_batches)
        sample_loader = sample_loader.slice(num_batches)

        print(f"train steps : {num_batches}")
        return sample_loader
```
![image](https://github.com/webdataset/webdataset/assets/52521165/068c88b3-32d0-4282-b972-92f562ff89e3)

![image](https://github.com/webdataset/webdataset/assets/52521165/567fd9ce-3b09-4d3c-b989-22dc7b687246)
unbalanced GPU utilization..
