### ISSUE TITLE
FAQ : What's the meaning of n in `with_epoch(n)`

### ISSUE THREAD

**Issue by HuangChiEn** [webdataset/webdataset#343]
According to the [thread](https://github.com/webdataset/webdataset/issues/250), i'm work in the `resample=True` + `.with_epochs(n)` method.
However, how to properly setup n in `.with_epochs(n)` remains unsolved in the above thread.

My first question : what is n `.with_epochs(n)` ? ([same question](https://github.com/webdataset/webdataset/issues/250#issuecomment-1474882735) in thread)
The answers I found : "[self.args.train_epoch_length](https://github.com/webdataset/webdataset/issues/250#issuecomment-1449384288)"、"[epoch length to n items](https://github.com/webdataset/webdataset/issues/250#issuecomment-1475780909)".

The most precise answer is "epoch length to n items", but I just simple use `wds.Webdataset(.)` wrapper, I can not expect how it depends on this. So, I just guess n is "epoch length to 'total_samples' items (samples)", and it will run  `n_step=total_samples // batch_size` for each epoch in this settings.

But,  I'm wrong, it gave an infinite loop for the following code snippet :
Basic info : `batch_size=16`, `num_worker=16` (in here I didn't expect worker matter to steps per epoch), `wds.WebLoader` to wrap webdataset.
```
# resampled=True : https://github.com/webdataset/webdataset/issues/225#issuecomment-1411143287
pair_ds = wds.WebDataset(str(shard_path), resampled=True).decode('pilrgb', handler=wds.warn_and_continue).to_tuple("jpg", "txt", handler=wds.warn_and_continue)
if self.img_transforms:
    pair_ds = pair_ds.map(warp_im_trfs, handler=wds.warn_and_continue)
if self.txt_transforms:
    pair_ds = pair_ds.map(warp_txt_trfs, handler=wds.warn_and_continue)

pair_ds = pair_ds.batched(self.batch_size, partial=False)
total_num_ds = self.total_num_ds * ratio
n_step = (total_num_ds // self.batch_size) 

# it should return pair_ds.with_epoch( int(n_step * self.batch_size) )
# but the trick : i just want it run 4 steps only per epoch for testing ~
return pair_ds.with_epoch(4*self.batch_size)

# wrap webloader
'''
loader = wds.WebLoader(
    pair_ds, 
    batch_size=None, 
    shuffle=False,   # laion ds doesn't have order between samples, so we don't need to shuffle 
    pin_memory=True, 
    num_workers=self.num_workers,
    prefetch_factor=2
)
return loader  #.batched(self.batch_size)
'''
```
![image](https://github.com/webdataset/webdataset/assets/52521165/99250e8d-fce9-4ce8-9353-8d223a49aa4d)

I also recall the [answer](https://github.com/webdataset/webdataset/issues/250#issuecomment-1475780909), may be n is just the number of steps (if epoch length to 'total_batch' items (batch)) per epoch. then i switch to the following code snippet : 
```
# ... the same code snippet 
pair_ds = pair_ds.batched(self.batch_size, partial=False)
total_num_ds = self.total_num_ds * ratio
n_step = (total_num_ds // self.batch_size) 

# it should return pair_ds.with_epoch( int(n_step) )
# but the trick : i just want it run 4 steps only per epoch for testing ~
return pair_ds.with_epoch(4)
```

But, infinite loop again.. boomb I'm wrong..
![image](https://github.com/webdataset/webdataset/assets/52521165/b779a9c6-8b53-48bc-af76-b5f3b4554612)

However, I reach the end of first epoch, it did run 64 steps, fortunately ~
![image](https://github.com/webdataset/webdataset/assets/52521165/0eea4fbb-f0f2-47b0-a7a3-44757d9d133a)

---

Conclusion: the above setup for `with_epoch(n)` expect to run 4 step per epoch, but the parameter n is not what i understand in the [thread](https://github.com/webdataset/webdataset/issues/250). Could someone please guide me about this **simple question** ?

Thanks folks ~

**Comment by HuangChiEn** [comment]
`n` is the number of step per epoch. The reason why `num_work` setup will affect the data samples in each batch is described in the following colab notebook :
https://colab.research.google.com/drive/1OFLZnX9y5QUFNONuvFsxOizq4M-tFvk-?usp=sharing

**Comment by tmbdev** [comment]
.with_epoch(n) is the same as islice(n)
