### ISSUE TITLE
How does shuffling work?

### ISSUE THREAD

**Issue by richardrl** [webdataset/webdataset#350]
When you do dataset.shuffle(...), does it shuffle the shards or does it shuffle samples within a shard?

**Comment by tmbdev** [comment]
The .shuffle(...) method shuffles samples. To shuffle shards, you need to use WebDataset(..., shardshuffle=True, ...)

Note that the best way to shuffle is this:

```
dataset = WebDataset(..., shardshuffle=100).shuffle(...) ... .batched(64)
dataloader = WebLoader(dataset, num_workers=..., ...).unbatched().shuffle(5000).batched(batch_size)
```

This will shuffle between shards, in addition to within shards.

**Comment by huongngo-8** [comment]
Hi! Thank you so much for taking the time to answer all of our questions. Just one question as a follow up - is the shard shuffling deterministic or is there some way we can set a seed to ensure it's deterministic? Thank you!

**Comment by DLKKILL** [comment]
> WebLoader

Could you please explain the role of webdataset.shuffle and WebLoader.shuffle respectively?

**Comment by FFrse** [comment]
Hi @tmbdev , I wanna ask what's the difference between .shuffle(5000) and .shuffle(1000) in WebLoader. If the total number of the dataset is 13000, then which way is better for shuffling?
