### ISSUE TITLE
Excess memory usage when generating short sequence clips

### ISSUE THREAD

**Issue by clane9** [webdataset/webdataset#354]
I'm using webdataset (v0.2.86) to stream a large dataset of videos. My pipeline is to decode the videos, split the videos into short clips, then shuffle the clips. I noticed however that this pipeline uses much more memory than the given shuffle buffer size. But if I disable shuffling or clipping, the memory usage is as expected. [Here](https://gist.github.com/clane9/6f12d2372ba00fb01adda1074e8c5a45) is a notebook with a minimal example you can hopefully use to reproduce. You can see in the log that the memory usage grows to 2x the buffer size. With my actual dataset, it continues to grow until I receive an OOM error. Thanks in advance for any help!

**Comment by tmbdev** [comment]
I'm not sure what exactly you expect to happen in that code. But if you `yield x[start:start+window]`, you retain the entire original array, not just the short clip. Since you are shuffling, you area retaining full length sequences from pretty much all sources.

You can probably fix that by `yield x[start:start+window].copy()` or `yield x[start:start+window]+0`

**Comment by clane9** [comment]
Thanks for the reply. You were right, `yield x[start:start+window].copy()` fixed the issue. I should have thought to try that. I did not expect it to matter bc in either case the buffer should contain (references to) the same data. In the first case, `N` references to `N` arrays. In the second case `K * N` references to clips of the same `N` arrays. If I was only pulling out one clip from each array, I would see your point. But since I'm taking all the clips, I still don't really understand. It doesn't matter though since the issue is fixed. Thanks again.

**Comment by clane9** [comment]
Ok nevermind I understand. Initially there are `N` unique array references but as you sample from the buffer eventually it will contain many more than `N`.
