### ISSUE TITLE
`pipe:s3cmd` or `pipe:aws s3 cp` ?

### ISSUE THREAD

**Issue by cgebbe** [webdataset/webdataset#358]
I've seen examples of both `pipe:s3cmd` or `pipe:aws s3 cp`. Is one recommended over the other?

**Comment by tmbdev** [comment]
It shouldn't make any difference; whichever works best from the command line for you.

The reason WebDataset uses pipe: and subprocesses for this is twofold:

- we need an I/O subprocess anyway, so it might as well be the native command
- you can pick the command that works best for you in your environment to access whatever server you need to access

Note that the pipe: IPC mechanism is extremely efficient on modern Linux systems.
