### ISSUE TITLE
custom batch sampler ?

### ISSUE THREAD

**Issue by benihime91** [webdataset/webdataset#359]
what is the best way to use a custom batch sampler in an multi-gpu/multi-node training setup ?

**Comment by tmbdev** [comment]
I'm not sure what you mean by a "custom batch sampler". Generally, WebDataset doesn't "sample batches", it just builds them up sequentially, optionally after shuffling.

If you want to compose batches in some fancy way (e.g., based on size), you can directly write an iterator function. Here is something that will ensure one class per batch (untested):

```
def one_class_per_batch(src, nclasses=10, batch_size=16):
    buffer = [[] for i in range(10)]
    for sample in src:
        cls = sample["cls"]
        buffer[cls].append(sample)
        if len(buffer[cls] == batch_size):
            result = buffer[cls]
            buffer[cls] = []
            yield result

...
ds = WebDataset(...)
ds = ds.shuffle(...).compose(one_class_per_batch)
...
```

Does that answer your question?

If you want to do something different, you always have the option of using `wids.ShardListDataset`, which just gives you an `IndexedDataset`, so you can "sample a batch" in any way you like. For efficiency, you still need to pay attention to locality of reference, however.

**Comment by benihime91** [comment]
hi this solves by use case where i was trying to same image batches according to image size. I did not know that the compose function existed but yeah thanks for the solution 😄
