### ISSUE TITLE
is there a way to sample data according to some sequence?

### ISSUE THREAD

**Issue by zhangvia** [webdataset/webdataset#367]
i got a huge dataset composed of large images which are extracted from video. i want to sample data like this:

chose a timestamp randomly，and get the next four frames from that timestamp. preprocess these images as a sample.

how could i use webdataset to implement this?

**Comment by floringogianu** [comment]
See this answer here, I used to achieve something similar: https://github.com/webdataset/webdataset/issues/203#issuecomment-1207103830

**Comment by tmbdev** [comment]
The recommended way is to precompute sampled sequences of five frames and then treat each collection of five frames as a batch.

If you don't want to do that, you can also take the following approach:

- split your long videos into shorter clips (or video sequences) of, say, 50 frames, and overlap them by five frames
- generate several five frame samples from each clip
-  shuffle the resulting five frame sequence

```
ds = WebDataset("video-clips-{000000..000999}.tar").decode()

def generate_clips(src):
    for sample in src:
        # assume that each video clip sample contains sample.000.jpg to sample.049.jpg images
        clip = [sample["%03d.jpg" % i] for i in range(50)]
        starts = random.choice(range(50-5), 10)
        key = sample["__key__"]
        for i in starts:
            yield {
               "__key__": f"{key}-{i}",
               "sequence": clip[i:i+5],
            }

ds = ds.compose(generate_clips).shuffle(1000)
```

You also have the option of storing image in order, one image per sample, and then relying on the image sequence within the shards. However, this is not recommended.
