### ISSUE TITLE
Combining multiple dataset on same key

### ISSUE THREAD

**Issue by LTMeyer** [webdataset/webdataset#370]
I am trying to train a model on different modalities (e.g. images, text, etc.). I want to be able to select which modality I use for training. Consequently, I created independent shards for each modality. Across modality the shards have the same size and contain the same keys. For instance, the data are organized as follow:
```
modality_a/
    shard_0.tar/
      key_0.png
      key_1.png
      ...
modality_b/
    shard_0.tar/
      key_0.npy
      key_1.npy
      ...
```

I understood that it was recommended to recreate a dataset archive for each set of modality (for instance a tar file containing only modality_a, another one merging modality_a and modality_b). However, this is not feasible for practical storage limitation. I would like to know if it was possible to have webdataset merging different datasets that have the same structure. The merged dataset should return unified samples based on matching keys.

The issue bears similarity with https://github.com/webdataset/webdataset/issues/335, except I don't want to access matching data from another source (like a small DB) but rather from another WebDataset.

[This repository](https://github.com/apple/ml-4m/blob/main/fourm/data/unified_datasets.py#L237-L317) already provides an ad hoc solution. I was wondering if it was possible to integrate a similar solution it to webdataset. If not, what would be the recommended implementation or approach?

**Comment by tmbdev** [comment]
This notebook explains how to associate different shards with one another ("column store").

https://github.com/webdataset/webdataset/blob/main/examples/column-store.ipynb

Note that by taking advantage of the `__url__` field, the code becomes very similar to the `.associate` method.

**Comment by LTMeyer** [comment]
Thank you @tmbdev, that works.
