### ISSUE TITLE
Question: why enforcing lowercase for WDS file suffix? 

### ISSUE THREAD

**Issue by YLouWashU** [webdataset/webdataset#371]
I noticed that the `group_by_keys` function in `tariterator.py` would by default lowercase the WDS file suffix. I'm wondering what is the motivation behind this? Is there way to turn this off? This is slightly confusing when the tar file contains files like "TestData.pth", but the loaded dict key is "testdata.pth"? Thanks!

**Comment by tmbdev** [comment]
Windows and Mac file systems are case independent. WebDataset therefore prefers that your datasets are case independent as well, since otherwise unpacking them on those other systems would cause problems. You can disable this by setting `lcase=False`

**Comment by YLouWashU** [comment]
Thanks for the explanation! I've buried in the Linux world for too long to
forget what the Mac and Windows side looks like. Can you point me to any
code snippet to set this flag when creating a WDS loader? Thanks!
