### ISSUE TITLE
Seed has limited effect on WebDataset

### ISSUE THREAD

**Issue by LTMeyer** [webdataset/webdataset#372]
# Context 

This issue is related to https://github.com/webdataset/webdataset/issues/370. We assume we have at least two WebDataset instances we want to sample in the same fashion. Passing the seed of the first dataset to the other and setting `shardshuffle` for all datasets should result in the same sampling.

# How to reproduce

As we are considering shard shuffling, let first have multiple shards. We make a shallow copy of one shard already present in the test data.
```bash
ln -s testdata/imagenet-000000.tgz testdata/imagenet-000001.tgz
```

Then, we create two WebDataset instances with shard shuffling enabled. The seed of the first shard is passed to the second one to have the same shuffling.

```python
ds1 = WebDataset("testdata/imagenet-{000000..000001}.tgz", shardshuffle=True)

ds2 = WebDataset("testdata/imagenet-{000000..000001}.tgz", shardshuffle=True, seed=ds1.seed)

for data1, data2 in zip(ds1, ds2):
    assert data1 == data2, f"{data2['__url__']} mismatches {data1['__url__']}"
```

We expect the assertion above to not raise any error, which is not the case. The assert may pass because of the tiny size of the fake dataset, but this is not consistent.

# Root cause

The problem comes from the fact the `seed` is not passed to the shuffling filter (c.f. https://github.com/webdataset/webdataset/blob/main/webdataset/compat.py#L157-L160). If we set the same seed for ds1 and ds2 above the assertion passes successfully.

**Comment by tmbdev** [comment]
I'll have a look and see whether I can clean up the seed issue.

However, for associating shards with one another, it's best to follow the suggestion in #370 ; that is, use the `__url__` metadata to find the corresponding shard, rather than trying to ensure that the two datasets use the same seeds.
