### ISSUE TITLE
ShardWriter Always Create an Empty Archive Upon Initialization

### ISSUE THREAD

**Issue by able2608** [webdataset/webdataset#376]
When creating a sharded dataset in python with `webdataset.writer.ShardWriter`, an empty tarfile was generated before any `ShardWriter.write()` or `ShardWriter.next_stream()` call. Upon closer inspection of the source code on the main branch, a `next_stream()` call was found in the constructor of class `ShardWriter`, which seems to be the reason of this behavior. I'm not sure if this is an intended behavior of `ShardWriter` as I'm new to `webdataset`, but I expect every shard to contain data and such empty 0th shard seems weird to me.

The code snippet I use is shown below: 
```
print(f"Reading list and verifying file exists...")
...
with wds.ShardWriter(out_pattern, maxcount=1e20, maxsize = 1e20) as sink:
    # The list to export later to reconstruct the split structure
    shards2fold = []
    # Go through all splits
        for i, fold in enumerate(cleaned):
            shards_in_the_fold = []
            print(f"Distributing files in the {i}th split...")
...
```
The output (truncated) of the above snippet is as below:
```
...
Reading list and verifying file exists...
# writing for_testing000000.tar 0 0.0 GB 0
Distributing files in the 0th fold...
...
```

Note that I'm distributing files to the shards manually instead of using the provided automatic method, as I want to prevent data from different sources mixing together while keeping them in the same dataset, hence the ridiculous `maxcount` and `maxsize`. I would call `next_stream()` manually when needed.

**Comment by tmbdev** [comment]
Shard 0 is not empty. The message just means that "I am starting to write this tar file now and it tells you how much it has written before it started this shard (nothing in case of shard 0).

**Comment by able2608** [comment]
I see. My bad.
