### ISSUE TITLE
NameError: name 'Iterable' is not defined. Did you mean: 'Iterator'?

### ISSUE THREAD

**Issue by li-li-github** [webdataset/webdataset#389]
`Iterable` is used without imported at
https://github.com/webdataset/webdataset/blob/7e33c40825c5157a0c5c4def050d4692b491b68f/webdataset/utils.py#L54

**Comment by tmbdev** [comment]
Thanks.

**Comment by DanTremonti** [comment]
Hi @tmbdev, has this issue been fixed?
