### ISSUE TITLE
Sequence Data 

### ISSUE THREAD

**Issue by Holasyb918** [webdataset/webdataset#392]
Hi 
webdataset==0.2.86
when I use webdataset, the data I need is a sequence that requires the current frame image and its previous and next 3 frames.
These frames come from 300,000 video clips. I save each clip as a sample inside a tar file. After that, I use compose + generate_clips to read this sequence.
![image](https://github.com/user-attachments/assets/1bbafb59-bd16-4c0d-8591-6619bf8e6830)

Then
![image](https://github.com/user-attachments/assets/2c15c862-9c98-4b48-9922-bd6eaf7c0ca3)

However, I've noticed that this method is extremely slow, and num_workers doesn't seem to have an effect.
What can/should I do?

**Comment by holasyb** [comment]
> problem solved;
just make sure num worker <= tar file num
issue closed

Webdataset is such a great work!

**Comment by Holasyb918** [comment]
problem solved
just make sure num worker <= tar file num
issue closed
Webdataset is such a great work!

**Comment by tmbdev** [comment]
Thanks. Sorry for not responding earlier, I was away at a conference.
