### ISSUE TITLE
WebDataset with a directory URL could fail due to missing class. 

### ISSUE THREAD

**Issue by maciej-adamiak** [webdataset/webdataset#399]
Please check whether [this line](https://github.com/webdataset/webdataset/blob/7175cdad56aebfa9d01e5e86dd2e2654629aac7e/webdataset/compat.py#L490) doesn't contain a spelling error. I don't see such a class in the  `webdataset.shardlist`  module.

**Comment by tmbdev** [comment]
Thanks; fixed.

**Comment by maciej-adamiak** [comment]
Thank you for introducing a fix!
