### ISSUE TITLE
DDP with Accelerate: you need to add an explicit nodesplitter to your input pipeline for multi-node training Webdataset

### ISSUE THREAD

**Issue by CONSTANT1386** [webdataset/webdataset#406]
I‘m using my Accelerator to prepare the dataloader, which is initialized and prepared as followed:
```python
tar_files = glob.glob(wds_path)
dataset = wds.WebDataset(tar_files, resampled=True).decode("pil").shuffle(1000).to_tuple("jpg", "txt").with_epoch(10000)
train_dataloader= DataLoader(dataset, batch_size=train_batch_size, num_workers=num_workers, collate_fn=collate_fn)
ip_adapter, optimizer, _, lr_scheduler = accelerator.prepare(
        ip_adapter, optimizer, deepcopy(train_dataloader), lr_scheduler
    )
````
But when the code execute this line
```python
for step, batch in enumerate(train_dataloader, start=step_in_epoch):
```
the following error happens:
`ValueError: you need to add an explicit nodesplitter to your input pipeline for multi-node training Webdataset.`
I also refer to to the [Using DDP with WebDataset in pytorch lightning #250](https://github.com/webdataset/webdataset/issues/250), but it seem be no helpful for acclerate case.
Could someone help me? I will very appreciate

**Comment by tmbdev** [comment]
You are apparently running in a multinode training environment. Doing that with the sequential webdataset library requires you to make a bunch of decisions, and one of them is how to split shards across nodes. That's a result of how PyTorch DataLoader works.

The recommended way of doing distributed training is with the wids library ("import wids"), which is a drop-in replacement for regular PyTorch datasets and handles distributed training the same way.

There are examples for multinode/multi-GPU training in the examples/ subdirectory.
