### ISSUE TITLE
I only get 1 key instead of three

### ISSUE THREAD

**Issue by NikiPshg** [webdataset/webdataset#407]
![изображение](https://github.com/user-attachments/assets/e285f56f-1657-461b-bd01-03437e09bf8e)
{'__key__': '000199', '__url__': '/content/train_tar.tar', 'speech.wav': (tensor([[0.0265, 0.0166, 0.0130,  ..., 0.0767, 0.0854, 0.0892]]), 48000)}

**Comment by tmbdev** [comment]
Most likely, your files are not adjacent in the .tar file. That is a requirement.

If you are creating your tar files with the `tar` command, you shoul use the `tar --sorted=name` option to achieve this.
