### ISSUE TITLE
How to decode numpy arrays that require allow_pickle=True

### ISSUE THREAD

**Issue by heimrabe** [webdataset/webdataset#410]
Hi thank you very much for your work. I am currently using TarWriter to create a custom tar file of a Dataset. In it I encode a numpy which requires the allow_pickle=True to be then decoded with numpy.load. Currently, is there a way to pass this flag to the numpy decoder if necessary? Or is the suggested way to save is as binary file and saving it as a pyd file? I do not think the two should be different once decoded.

**Comment by Akhil-CM** [comment]
you could pass a callable to `.decode(customCallable)`. which takes in two arguments `key` and `value`. See this here:
https://github.com/webdataset/webdataset/blob/1e47aa3de66a23fed0d0f28e787c46beb98ac538/webdataset/autodecode.py#L543

**Comment by tmbdev** [comment]
WebDataset by default uses allow_pickle=False for .npz and .npy extensions by default. That is the safer and more common default; it's generally not such a good idea to put objects into numpy arrays.

If you do want to decode .npy or .npz data with allow_pickle=True, you can do so by adding a decoder for these extensions that calls numpy.load with allow_pickle=True, or you can just do the decoding in a .map(sample) before the default decoders. Either way, it is something you should do explicitly.

The preferred way is to use .pyd for objects that require pickling, and .npy and .npz for pure numpy arrays.
