### ISSUE TITLE
(question) Confused by slowdown after using ShardWriter instead of TarWriter

### ISSUE THREAD

**Issue by RuABraun** [webdataset/webdataset#86]
Hello, 
thanks for creating this tool. My setting is I have a dataset that does not fit in RAM and work on an NFS cluster with slow IO speeds (no SSDs).

I'm confused because when I train with the training split into shards (each is 3G) instead of a single tar I get an order of magnitude slowdown. I'd like to understand what webdataset does that causes this.

I thought that one point (among others) of webdataset was that because one uses an iterable dataset, one can load part of dataset, use that for generating batches of samples, and in the meantime load the next part in the background and switch to it once all samples in the first part have been used. To get around the issue of not being able to shuffle one can split the whole dataset into some files (shards), and shuffle those (as well us shuffling inside of a shard).

I don't understand why having to load the shards (files) would cause such a large slow down since there are not that many (~70). If it matters the data is saved in binary format (there is no encoder and the decoder just recovers the objects).

edit: Have I understood the [code](https://github.com/webdataset/webdataset/blob/81deb0aae9470a8aebed10538c6eaabfb5ac0149/webdataset/tariterators.py#L103) correctly that a tarfile is not actually read in one go but instead the contained files are read one by one?

**Comment by tmbdev** [comment]
> I'm confused because when I train with the training split into shards (each is 3G) instead of a single tar I get an order of magnitude slowdown. I'd like to understand what webdataset does that causes this.

You are probably reading multiple shards from the same rotational disk drive (if you're using `num_workers > 1`, causing it to perform random seeks. The reason you are not seeing that when you use a single .tar file is that a single .tar file can't be split among multiple workers so only one worker tries to read it.

This is not a WebDataset limitation, it's a limitation of your hardware. That is, a rotational drive can deliver about 200 Mbytes/s when you read only a single shard from it, but if you use any I/O pattern that results in random access (e.g., multiple shards, individual files, LMDB, etc.), that can drop to 20 Mbytes/s. To get the maximum I/O bandwidth of 200 Mbytes/s from a single rotational drive, it's best to use `num_workers=1`. 

If you have multiple physical drives available, you can distribute shards across them and WebDataset will read in parallel from multiple drives. If  you're using NFS as your network file system, obviously that requires some bookkeeping on your part.

The AIStore object store is an alternative that makes this easier.

> Have I understood the code correctly that a tarfile is not actually read in one go but instead the contained files are read one by one?

That's correct, and it's usually the right behavior for WebDataset. However, in your case, you may benefit from reading the data as quickly as possible; you can achieve this by using something like:

```
url = "pipe:mbuffer -m 4G /nfs/dataset/train-{000000..000999}.tar"
ds = wds.WebDataset(url, ...)
```

You might even do something like this:

```
url = "pipe:flock /tmp/shard.lock -c 'cat /nfs/dataset/train-{000000..000999}.tar' | mbuffer -m 4G"
ds = wds.WebDataset(url, ...)
```

This will use a lock to ensure that only one worker at a time accesses the NFS directory. It will then read the shard as quickly as possible and buffer the data in memory.

**Comment by tmbdev** [comment]
Please let me know if that fixes your issue.

**Comment by RuABraun** [comment]
Thank you very much for the elaborate answer. I will try your suggestion out!

**Comment by RuABraun** [comment]
Hi @tmbdev looking at webdataset again and have a question about IO in the context of webdataset. Can one get a performance speedup just because of doing IO sequentially instead of randomly, but while still doing the same number of read calls? I had always understood that the benefit from sequential IO was that, since there's no ambiguity as to what data will be read next, you can always do read operations that read in a lot of data at once (effectively reading multiple files at once), instead of reading file by file. But based on the default implementation of webdataset (which reads file by file) and what you talk about [here](https://www.youtube.com/watch?v=kNuA2wflygM), apparently there is a benefit to doing sequential IO even if one is not "batching" the read operations?

**Comment by tmbdev** [comment]
There are two kinds of files we're talking about: the shards and the sample files contained within the shards. WebDataset reads many sample files with a single read() call, and it reads all those files sequentially.

The benefits from sequential reads occur at several levels. At the level of disk hardware, sequential reads avoid the head seeking behavior (or analogous overhead on SSD's). At the level of network file systems, sequential reads can be streamed from the file server without any round trips.

**Comment by RuABraun** [comment]
> WebDataset reads many sample files with a single read() call

Doesn't that contradict your earlier statement?

>> Have I understood the code correctly that a tarfile is not actually read in one go but instead the contained files are read one by one?

> That's correct, and it's usually the right behavior for WebDataset.
