### ISSUE TITLE
How to flatten a webdataset

### ISSUE THREAD

**Issue by Moymix** [webdataset/webdataset#91]
Hi all,

I have a dataset like that:

0001.png
0001.captions
0002.png
0002.captions

where "0001.captions" contain multiple catptions for the png file like:

A boy is playing games with a man.
A man is playing games with a boy.

During the training phase, I wish to get a "flattend" sample like:

0001.png --- A boy is playing games with a man.
0001.png --- A man is playing games with a boy.
0002.png ---  A man is running on the road.
0002.png --- A man is running after a car.

**Comment by tmbdev** [comment]
You can write something like:

```
def expand_captions(src):
    for image, captions in src:
        for c in captions.strip().split("\n"):
            yield image, c
```

You can put this into your pipeline with something like:

```
ds = WebDataset(...).to_tuple("png", "captions").decode(...).then(expand_captions).shuffle(10000)
```

(It's worth considering writing the expanded dataset to disk first and then just training on the expanded dataset directly.)
