### ISSUE TITLE
404 API page of documentation

### ISSUE THREAD

**Issue by eliphatfs** [webdataset/webdataset#92]
The link through https://webdataset.github.io/webdataset/ to https://webdataset.github.io/webdataset/api/index.html results in a 404 not found error.

**Comment by tmbdev** [comment]
Thanks. They should be available now.

**Comment by wailay** [comment]
I dont want to create a new issue, but the documentation appears to be down since today.  https://webdataset.github.io/webdataset/

**Comment by tmbdev** [comment]
Thanks. I have to see whether I can update it tomorrow.
