### ISSUE TITLE
Online filtering

### ISSUE THREAD

**Issue by hutec** [webdataset/webdataset#96]
Is there a recommended way to apply online filtering to a dataset either on `webdataset` level or PyTorch `Dataset` level?
An example use case would be training on a subset of ImageNet classes without needing to regenerate the tar files.

Or is this something out of scope of `webdataset`/`IterableDataset`?

**Comment by tmbdev** [comment]
By "filtering", you mean selecting a subset of the dataset? As far as WebDataset is concerned, processing is just a chain of iterators operating on a stream of data, so you can select, reorder, and transform any way you like.

There is a shorthand for selecting samples:

```
def selection(sample):
    return "training" in sample["__key__"]

ds = WebDataset(...).select(selection).decode(...).etc...
```

Note that this will still read all samples but then discard the samples it doesn't want/need based on the selection function. That may seem inefficient, but it is usually faster than random access anyway.

When you train on very small subsets of the original dataset (less than 10%) and you need maximal I/O performance, you may want to prefilter the data based on some criteria and generate a new dataset representing just that subset.

**Comment by hutec** [comment]
Thanks, this is exactly what I envisioned.

**Comment by borisdayma** [comment]
Related to this question, would it make any sense to be able to read only some of the data files (for example `item.json` which would contain image dimensions), select items based on it, and then only load the entire items.

The idea would be to be able to create any subset of the data by only reading smaller files (metadata instead of full media files).

**Comment by m3at** [comment]
@borisdayma I think you can already, try something like:

```python
def check(x):
    x["my_filter"] = read_json(x["item.json"])["my_property"] > 42
    return x

wds.WebDataset(...).map(check).select(lambda x: x["my_filter"]).decode(...)
```
